main.py, models.py, tests/unit/test_main.py, utils.py
Description of the change
----------------------------
This PR creates a method to send an event informing some change happened to an EVC.
The method is called when an EVC is created, update, deleted, deployed, undeployed and when its path changes.
=> Send events when something happens to an EVC

storehouse.py
Some log messages were changed from info to debug,
disabling unnecessary messages
Fixes #25
=> Change log level of mef_eline.storehouse

.travis.yml
Test PR to see how codecov works.
=> Add codecov to report coverage

ui/k-info-panel/list_connections.kytos
Fix #61 
Pressing the button "List installed EVC" is not displaying the circuit´s information in the right panel.
Fixed the initial call to populate the circuits list.
Fixed the API call response to check invalid data. (Invalid data breaks the rendering engine)
Increased the panel width to display all the data.
=> Fix panel to display EVC data

ui/k-info-panel/list_connections.kytos
Fix #63 
For production, the list of circuits can be long, so some features are needed to help the operator, such as sorting and filtering the columns.
Added Kytos table component sorting feature, and a filter field where the operator can search values for each column.
=> New feature to sort and filter columns in circuit list

main.py, models.py, openapi.yml, tests/unit/test_main.py
Added endpoints to add, get and delete metadata of an EVC.
Fixes #73
=> Create endpoints to manage EVC metadata

tests/unit/test_main.py, ui/k-info-panel/show_circuit.kytos
Fix issue #92.
New feature to edit EVC.
The "Circuit detail" panel enters in edit mode with fields enabled to edit.
For now it is possible to edit the fields:
- name
- enabled (boolean)
- dynamic backup path (boolean)
- priority
- bandwidth
- queue
- uni-A DPID
- uni-Z DPID
- Tag values
The user must hit the "Save EVC" to save the changes.
=> [Feature] UI edit EVC

openapi.yml, utils.py
Fix #117.
New components created to reflect the way paths are defined when creating an EVC.
=> Change openapi spec for circuit creation

CHANGELOG.rst, kytos.json, setup.py, ui/k-info-panel/list_connections.kytos, ui/k-info-panel/show_circuit.kytos
Fix issue #148
UI code is changing the width of the Kytos right panel, and it reflects on all NApps.
This PR change the behavior modifying the width on UI creation and change it back to original on UI destroy.
=> Fix UI kytos panel

CHANGELOG.rst, kytos.json, settings.py, setup.py
Adjustment in the settings to make it comply with the change applied at PR #101. PR #101 landed without this change by mistake.
=> Fix WAIT_FOR_OLD_PATH according to PR 101

.gitignore, setup.py, tests/unit/models/test_evc_base.py, tests/unit/models/test_evc_deploy.py, tests/unit/models/test_path.py, tests/unit/test_main.py
Increase `mef_eline` test coverage to 81%.
=> Increase test coverage

CHANGELOG.rst, ui/k-info-panel/list_connections.kytos
Replace the list filter coded with pure Javascript with Vue code. The functionaly remains the same.
=> Optimize list filter

tests/unit/models/test_path.py, tests/unit/test_main.py
=> Fixed failing tests after core id changes

controllers/__init__.py, main.py, tests/unit/test_main.py
Fixes #193 
It's on top of PR #195 to facilitate merge conflicts.
=> Enhanced EVC find one

CHANGELOG.rst, ui/k-info-panel/show_circuit.kytos, ui/k-toolbar/main.kytos
Fix #202 
- Added ``service_level`` UI component on ``k-toolbar`` and made it editable.
I've also taken the opportunity o fix the editable `priority` as `sb_priority`. 
- Created an EVC with `service_level: 6`
- Updated `service_level` to 4:
=> [Feature/UI] service_level component

main.py, models/evc.py, tests/unit/models/test_evc_deploy.py
Fix #238 
With this PR it is verified that current_path is not empty. If it is, the corresponding circuit is discarded.
=> Update check_list_traces for execute_consistency

CHANGELOG.rst, openapi.yml, tests/unit/test_main.py
=> Added metadata to EVC schema

CHANGELOG.rst, main.py, models/evc.py, tests/unit/models/test_evc_deploy.py, tests/unit/test_utils.py, utils.py
This is a draft PR to give a little help to @gretelliz, I cherry picked her last commits on PR #280, Gretel, feel free to take over this PR and update the rest as needed
This PR is backported to 2022.3.
Same local tests as documented in PR #280.
=> fix: update function `check_list_traces` for consistency check with bulk traces - backport to 2022.3

db/models.py
Related to issue #306
Added a better detailed error message for the pydantic validation to help identify the cause of the related issue
=> Updated pydantic validatation error message

CHANGELOG.rst, ui/k-info-panel/show_circuit.kytos, ui/k-toolbar/main.kytos
Fix #263 
This PR fixes the issue about the values not reseting properly. 
It affects the form for request a new circuit and depends on the latest Kytos-NG UI library installed.
Select the Mef-Eline item
Complete form to create a circuit
Click button "Request Circuit"
All form data must be empty after the submit
=> Clear circuit values ​​after submitting the form

tests/unit/models/test_evc_base.py, tests/unit/models/test_evc_deploy.py, tests/unit/models/test_link_protection.py, tests/unit/models/test_path.py, tests/unit/test_controllers.py, tests/unit/test_db_models.py, tests/unit/test_scheduler.py, tests/unit/test_utils.py
Closes #343 
Refactored the tests to `pytest`
`test_link_protection.py` is being refactored in PR #349 
Run `tox`
=> Tests refactor with pytest

CHANGELOG.rst, kytos.json, main.py, models/evc.py, setup.py, tests/unit/test_main.py
Release `2022.3.3`. This was backported from PR #375 
For more information, check out PR #375
=> [release 2022.3.3] fix: Prevent race conditions in failover_path

CHANGELOG.rst, kytos.json, main.py, models/evc.py, setup.py, tests/unit/test_main.py
Release `2023.1.1`. This was backported from PR #375 
For more information, check out PR #375
=> [release 2023.1.1] fix: Prevent race conditions in failover_path

CHANGELOG.rst, ui/k-info-panel/show_circuit.kytos, ui/k-toolbar/main.kytos
Closes #260 
Adapted UI so it can handle list when a circuits has a list of ranges as TAG values
Created circuit through the UI
Updated circuit
Tested error possibilities related to TAG values
=> Adapted UI to list of ranges

CHANGELOG.rst, ui/k-info-panel/list_connections.kytos, ui/k-info-panel/show_circuit.kytos, ui/k-toolbar/main.kytos
Related to https://github.com/kytos-ng/ui/issues/35
Summary
This PR updates the UI to the Vue3 compatibility framework.
It requires the latest UI to work.
=> Upgrade UI to Vue3

CHANGELOG.rst, ui/k-info-panel/show_circuit.kytos
Closes #492 
Moved every method for EVC details to `mounted()`
Now the EVC details waits for node names to be loaded.
UI tested
N/A
=> Adding loading message to EVC details

CHANGELOG.rst
=> docs: fixed changelog

CHANGELOG.rst, ui/k-info-panel/show_circuit.kytos
Closes #N/A
A new modal component was added to the UI repository. This pull request makes it so that the mef-eline UI now utilizes the new modal component.
The new modal component was used on a single EVC and it functioned as should.
Description - UI repo in which the new modal component was implemented
- https://github.com/kytos-ng/ui/pull/80
=> Mef-Eline Modal Utilizes New Modal Component

README.rst
---
- Updated subscribed
- Updated published
Closes #546
---
This MR seeks to update the README section with events that are published/subscribed in the codebase.
=> Issue 546 - Update README

CHANGELOG.rst, kytos.json, main.py, models/evc.py, models/path.py, openapi.yml
Closes #581 
Added redeploy feature `try_avoid_same_s_vlan` to try to avoid the previous s_vlan in the previous `current_path`
Redeployed EVC
N/A
=> Backport: Added redeploy feature to avoid s_vlan 2024.1.9

CHANGELOG.rst, ui/k-info-panel/show_circuit.kytos
Closes #584
Added checkbox to decide whether to avoid `s_vlan` when redeploying.
Tried UI
=> Added UI option to not try to avoid s_vlan

CHANGELOG.rst, ui/k-info-panel/show_circuit.kytos, ui/k-toolbar/main.kytos
Closes #647 
Added `max_path` option to UI
Created EVC, modified it and redeployed it
N/A
=> [UI]: Added `max_paths` to UI

.github/workflows/main.yml
Closes #677 
Fixed GH actions tox deps. Related to https://github.com/kytos-ng/kytos/issues/584
changelog update not needed in this case
N/A
N/A
=> chore: fixed GH actions tox deps
