kytos-ng/mef_eline

main.py

This PR fixes #22.
Description of the change
-----------------------------
A fix was implemented to prevent race conditions when mef_eline consistency check routine is run at the same time as the creation of an evc: both of them will call evc.deploy() and it may result in duplicated flows being created for the same evc. I've run the unit tests and all of them are passing after the change. I've also run the end-to-end tests, specially the one created to validate this behavior (as documented in #22) which was run 10 times, and they are all passing (except the ones not related to this PR).
Release notes
---------------
- Fix a race condition when mef_eline's consistency check runs at the same time of the creation of a evc.

Fix race condition when mef_eline consistency runs at the same time as creation of an evc

---

main.py

Load EVCs on startup, so they will also be loaded when the
NApp is reloaded.
Previously EVCs were loaded only when a new interface was created.
Fixes #19

Load EVCs on startup

---

exceptions.py
models.py
tests/unit/models/test_evc_deploy.py
tests/unit/models/test_link_protection.py
tests/unit/test_main.py

Fixes #26 
Description of the change
----------------------------
If flow_manager returns an error code, stop the deployment and uninstall already installed flows, keeping the EVC inactive.
Tests
-----
New unit tests were created for this new behavior and old tests needed to be slightly modified.

Roolback deployment when flow_manager fails.

---

main.py
models.py
tests/unit/test_main.py

Fixes #28
Description of the change
=================
Priority was not being used in the flows. Now they
are used if defined, and the EVCs are redeployed if
the priority changes.
Main changes
---------------
- priority default value changed from 0 to -1 (allowing priority 0 to be used);
- if `priority > -1` then a priority field is included in the flow mod;
- if `priority == -1` then no priority is included in the flow mod and it will be the switch's default.
- if `priority` is updated, then the EVC is redeployed.

Include flow priority

---

main.py
openapi.yml
tests/unit/test_main.py

For now, only the API definition for review

Create an API endpoint to redeploy an EVC

---

ui/k-toolbar/main.kytos

New input autocomplete for DPIDs to help the user to write/select the value to create EVCs.
Since it is a new component it checks if the UI is updated, otherwise it will use the old input component.

New input autocomplete for DPID

---

main.py

Fixes #38
When EVC is `inactive`, it was redeployed on update only if the update is enabling it.
If the EVC was inactive due to an invalid primary path, an update on that path would not trigger redeploy
Now, redeploy is always called if the EVC is enabled.

On update, try to redeploy if EVC is enabled.

---

main.py
models.py
tests/unit/models/test_evc_base.py

Fixes #37
When `queue_id` was updated, the EVC was not being
redeployed, so the queue was not been reflected in
the flows.
A list of EVC attributes requiring redeploy when updated
was created to make it easier to redeploy.

Redeploy EVC when queue_id is updated

---

ui/k-info-panel/show_circuit.kytos

Fix #70 
In circuit details, the flag icons are swapped (True are X, and False are Check).
Replaced the icons to the correct values.

Fix boolean icons with swapped values

---

models.py

Fixes #79 
This PR will remove the call for `Link.use_tag`, which is deprecated by Kytos core. mef_eline is also calling `Link.get_next_available_tag()`, which happens to do what `use_tag` was doing.
N/A

Remove deprecated call for Link.use_tag

---

models.py

Fixes #77 
Added a exception handler for `remove_current_flows()`, which could raise a FlowModException if some of the switches in the current path lost connection or any other error from flow_manager.
N/A

Add exception handler for remove_current_flows

---

kytos.json
main.py
models.py
requirements/run.in
settings.py
setup.cfg
tests/unit/models/test_link_protection.py
tests/unit/test_utils.py
utils.py

Fixes #33 
Existing EVCs are loaded on Kytos startup, and were always redeployed, leading to some problems as described in the linked issue. Now, before trying to redeploy, it is checked if the old path the EVC used is still working. If it is, the EVC is marked as active and no further action is taken. If after a specific amount of time (configurable) the old path is not working, then the EVC is redeployed.

Do not always redeploy EVCs on startup

---

ui/k-info-panel/list_connections.kytos
ui/k-info-panel/show_circuit.kytos

Fixes #64
In the UI the DPID is displayed but it has no meaning for the operator and some human readable alias must be provided
Ex: 00:00:00:00:00:00:00:01 -> fortaleza
This PR replace the DPID (00:00:00:00:00:00:00:01), interface (00:00:00:00:00:00:00:01:40) and port (40) IDs with alias provided by the topology NApp in the metadata attribute. These metadata must be created using topology rest endpoints.
In the panel to list the circuits is possible to filter using the switch name and interface name.
In the panel with circuit details it is possible to visualize the IDs and aliases. This PR also provides the link name for the circuit paths, since it is also retrieved from metadata.
- Improved mef_eline UI to add aliases for switch, interface, port and links.

Add dpid, interface, link aliases.

---

main.py
tests/unit/test_main.py

Fixes #100 
THis PR is a simple replacement of the approach used by mef_eline to decide when re-deploy an EVC once the sdntrace-cp failed. The current approach is based on a timer. The proposed solution will use a execution cycles/rounds counter. By using the rounds counter instead of timers, we avoid that a longer execution at the beginning leads to the EVC being redeployed even in the first execution round (of course, assuming that sdntrace-cp will fail). In other words, by using timers we increase the possibility of "giving more opportunities to sdntrace detects when the EVC is actually running".
N/A

Replace timer with rounds counter to decide when redeploy once sdntrace-cp fails

---

models/evc.py

Fixes #102 
This PR adds some sort of error handler for sdntrace-cp calls. Any error returned by the sdntrace-cp API (`status_code >= 400`) will result in a log entry and a empty response (which preserves the behavior of caller method).
Additionally, the `EVC.check_traces()` was modified to add `log.warn` when a trace fails. Thus, the administrator can have records about trace failures.
N/A

Add error handler for sdntrace-cp calls

---

ui/k-info-panel/show_circuit.kytos

Fix issue #104 
To edit the DPIDs fields the user must know exactly the ID input.
This PR adds the feature of autocomplete to the DPIDs fields, based on parcial inputs.
It also fix some styles of the edit button that was unaligned. 
OBS: it must use UI version 1.4.3-beta.2 or later.

Add feature of autocomplete to DPIDs fields

---

storehouse.py
tests/unit/test_main.py
tests/unit/test_storehouse.py

Fixes #108 
Mef_eline's storehouse already leverages `threading.Lock` to protect its data against race conditions, more specifically during the update phase. This PR extends the Lock usage to also coverage the retrieve phase along with the `get_stored_box()` method. This was necessary because in some conditions the user may request to retrieve data right before storing new data. The retrieve process is executed asynchronously, and when the data is ready it can overrides the updated data (if they happen to run at the same time, or their threads get scheduled in parallel).
I've run the end-to-end tests with 200 repetitions and no further error was reported:
```
( for i in $(seq 1 200); do echo $i $(date); python -m pytest tests/test_e2e_12_mef_eline.py::TestE2EMefEline::test_delete_schedule; …
```

Add Lock to prevent race conditions at storehouse get_stored_box method

---

requirements/dev.txt
requirements/run.txt

It turns out when [`requests` was pinned on version `2.27.0`](https://github.com/kytos-ng/mef_eline/blob/master/requirements/run.txt#L62) on this PR #115, I should've also `pip-compile` upgraded its transitive dependencies like `certifi`, `idna` and `urllib3`, otherwise they'd end up with prior pinned versions that would leave margin for conflicts, this is one of the trade off of having stricter transitive dependencies, but once they're all set it should be easier with documented guidelines how to keep this handled smoothly in the future as we need to roll out upgrades.
FYI, I've mapped an issue on this repo https://github.com/kytos-ng/kytos-ng.github.io/issues/14 to document some guidelines to have a deterministic and clear way on how to deal with upgrades and what to look for to make …

[Fix] Upgraded transitive deps from `requests` on `requirements/run.txt` 

---

models/evc.py
tests/unit/models/test_evc_base.py

Fixes #124 that @italovalcy has reported (thanks for mapping and double checking the error there)
- Fixed `get_id_from_cookie` leading zeros issue
I was going to bump a version, but since the release hasn't happened yet, it didn't set a new version

[Fix] `get_id_from_cookie` leading zeros issue

---

tests/unit/models/test_link_protection.py

Fix #112.
This was done by trial and error. As the objective of the tests is to check if `handle_link_up` is actually calling `deploy_to_path` only once, it makes sense to zero the counter right before calling `handle_link_up`.
I let the tests running 100 times, with no errors.

Fix call count on link up/down handling

---

ui/k-info-panel/show_circuit.kytos

Related to issue #91 
In the EVC edit form the user needs to know the value for DPID to edit the field.
This PR adds the interface name to the autocomplete field to help the user to select the correct value.

[Feature] UI edit EVC - Add node names for DPID autocomplete fields

---

ui/k-toolbar/main.kytos

Fix #118 
In the EVC create form all values remain in the fields after the user hit the "Request Circuit" button.
This can cause some confusion for the user because the success/failure message appears in the notifications panel.
This PR clears the form fields if the create action is successful.
If it fails for any reason, the values remain on the form.

[Fix] UI create EVC - Clear fields if create EVC is a success

---

main.py
tests/unit/test_main.py

Fixes #128 
- Fixed GET `/v2/evc/<circuit_id>` to return 404

[Fix] GET `/v2/evc/<circuit_id>` 404

---

main.py

Fixes #131 
This PR leverage the `EVC.Lock` mechanism to also protect against race conditions during the removal of an EVC. Without this protect it might happen that mef_eline leaves some alien flows in flow_manager when the removal of an EVC happens at the exact same time when the EVC is being processed by the consistency check routine (such as the example shown on issue #131).
All the unit tests were executed and no surprises were noticed.
I've also repeated 20 times the end-to-end test that revealed this issue and no more error was reported:
```
export TESTS=tests/test_e2e_10_mef_eline.py::TestE2EMefEline::test_080_create_and_remove_ten_circuits_ten_times
( for i in $(seq 1 20); do python -m pytest $TESTS; done ) 2>&1 | tee log-mef_eline_test_080.log
20
0
```
- Added EVC.Lock mechanism …

Add lock to prevent race conditions when removing the EVC

---

CHANGELOG.rst
kytos.json
models/evc.py
setup.py
tests/unit/models/test_evc_deploy.py
tests/unit/models/test_link_protection.py
utils.py

`mef_eline` manages and consumes tags when circuits are either provisioned or removed, and this resource `available_tags` needs to be stored and loaded when switches connect again or reboot, so I added a function to publish ``kytos/mef_eline.link.available_tags``  for `topology` to subscribe, which is being delivered [on this PR 46](https://github.com/kytos-ng/topology/pull/46)
version `[2.7.0] - 2022-01-19`
-  Added utils ``notify_link_available_tags`` function
-  Publish ``kytos/mef_eline.link.available_tags`` event
-  Hooked ``notify_link_available_tags`` when choosing or making vlans available

[Feature] Publish `available_tags` event when vlans are allocated or removed

---

CHANGELOG.rst
kytos.json
setup.py
ui/k-info-panel/list_connections.kytos
ui/k-toolbar/main.kytos

Fix issue #138 
The "List installed EVC" button does not re-render the contents of the panel. The user must close the panel clicking the "X" button and click the "List installed EVC" button again.
This PR fixes this issue, forcing the panel that list the EVCs to be destroyed and the rendering of the content.
It needed a timeout between the calls because they are asynchronous.

Fix list button not rerendering the content

---

CHANGELOG.rst
kytos.json
setup.py
ui/k-info-panel/show_circuit.kytos

Fix #141 
If the EVC is created without the tag field, the EVC edit couldn´t handle it.
This PR makes the tag as an optional data, and render the input fields so the value can be inserted.

Make tag field optional and editable

---

CHANGELOG.rst
kytos.json
setup.py
ui/k-info-panel/show_circuit.kytos
ui/k-toolbar/main.kytos

Fix #145
In the form to create EVC, the endpoint autocomplete displays the result list without the scrollbar.
This PR fixes the width issue that caused the issue with the scrollbar in the create form, making the autocomplete style more specific to avoid overriding from generic styles.

Fix UI autocomplete result list width

---

CHANGELOG.rst
models/evc.py
tests/unit/models/test_evc_deploy.py

Q-in-Q had been removed because of issues with Noviflow. Now the issue is solved, so again we can have Q-in-Q, with the cliente VLAN being changed in the first switch.
Fix #154

fix: Change client vlan on first switch

---

CHANGELOG.rst
models/path.py
settings.py
tests/helpers.py
tests/unit/models/test_path.py

Related to #156 
This pull request implements the `DynamicPathManager.get_disjoint_paths` as per [blueprint EP029](https://github.com/kytos-ng/kytos/blob/master/docs/blueprints/EP029.rst). Basically, the following contributions can be listed from this PR:
- Improved `DynamicPathManager.get_paths` to also supports `max_paths` parameter and then request more paths from pathfinder (default to 2, [which is also the default on pathfinder](https://github.com/kytos-ng/pathfinder/blob/61cfcde85b670a8bfe79722279aebab507801e2c/main.py#L113))
- Added `DynamicPathManager.get_disjoint_paths `, which calculates the maximum disjoint paths from a given "unwanted_path" (typically the currently in use path) using the approach described in blueprint EP029
- Improved unit test coverage for `models/path.py` …

Adding disjoint path as per EP029

---

CHANGELOG.rst
db/models.py
models/evc.py
openapi.yml
scripts/001_rename_priority.py
tests/unit/models/test_evc_base.py
tests/unit/test_db_models.py
tests/unit/test_main.py

Fixes issue #192
- Added ``service_level`` EVC attribute to set the service network convergence level, the higher the better
- ``priority`` has been renamed to ``sb_priority`` (southbound priority), ``./scripts/001_rename_priority.py`` can be used to update EVC documents accordingly
- ``priority`` is no longer supported in the API spec
The `service_level` is only being set, it'll be used on issue #179 
```
❯ python scripts/001_rename_priority.py
Rename evc priority as sb_priority updated: 1
❯ python scripts/001_rename_priority.py
Rename evc priority as sb_priority updated: 0
```
I've also explored it locally setting `service_level` and `sb_priority`:
```
{
"3430a0de7e054b": {
...
"id": "3430a0de7e054b",
"metadata": {},
"name": "epl",
"owner": null,
"primary_links": [],
"primary_path": [], …
```

[Feature] `service_level` and `sb_priority` attributes

---

CHANGELOG.rst
main.py
tests/unit/test_main.py

Fixes #179 
This PR is on top of PR #196 
- EVCs with higher service level priority will be handled first during network convergence, including when running ``sdntrace_cp`` consistency checks.
In addition to unit tests, I've also explored it with three EVCs (I've temporarily included some new logs), simulated link down and consistency checks:
```
2022-10-05 15:46:11,621 - INFO [kytos.napps.kytos/mef_eline] [main.py:658:handle_link_down] (thread_pool_app_1) Event handle_link_down Link(Interface('s1-eth3', 3, Switch('00:00:00:00:00
:00:00:01')), Interface('s3-eth3', 3, Switch('00:00:00:00:00:00:00:03')))
2022-10-05 15:46:11,622 - INFO [kytos.napps.kytos/mef_eline] [main.py:664:handle_link_down] (thread_pool_app_1) handle_link_down checking evc b3153652185742 name evpl1 service_level 7 …
```

[Feature] Prioritized network convergence based on `service_level`

---

CHANGELOG.rst
controllers/__init__.py
db/models.py
models/evc.py
models/path.py
openapi.yml
setup.cfg
tests/unit/models/test_evc_base.py
tests/unit/models/test_path.py
tests/unit/test_main.py

Fixes #136 
- Added support for constrained paths for primary dynamic paths and failover paths, ``primary_constraints`` and ``secondary_constraints`` can be set via API.
- I'll cover e2e tests on this issue https://github.com/amlight/kytos-end-to-end-tests/issues/165 
- I explored locally with a ring topology, similar to the one documented in the blueprint. 
```
100G, "blue"
+------------------------------------------+
|                 link a                   |
|                                          |
|                                          |
+---+----+           +--------+           +----+---+
|        | 100G,"red" |        | 100G,"red" |        |
|  SW1   +-----------+  SW2   +-----------+  SW3   |
H1-------+        |  link b   |        |  link c   |        +-----H2
|        | …
```

[Feature] pathfinder CSPF integration

---

models/evc.py

Fixes #206 
Quick PR replacing `log.warn` with `log.warning` to fix the deprecation notice.

Replaced `log.warn` with `log.warning`

---

CHANGELOG.rst
controllers/__init__.py
main.py
openapi.yml
tests/unit/test_controllers.py
tests/unit/test_main.py

Fixes #199 
This PR is on top of #198
- Documented ``GET /v2/evc?archived`` query arg on openapi.yml
- ``GET /v2/evc?archived=true`` will only return archived EVCs
- Fixed found but unloaded message log attempt for archived EVCs
- Explored the three cases (default|false, true and null)
```
❯ http localhost:8181/api/kytos/mef_eline/v2/evc | jq -r | rg archived                                                                                                          
"archived": false,
❯ http localhost:8181/api/kytos/mef_eline/v2/evc?archived=true | jq -r | rg archived
"archived": true,
"archived": true,
"archived": true,
❯ http localhost:8181/api/kytos/mef_eline/v2/evc?archived=null | jq -r | rg archived
"archived": true,
"archived": false,
"archived": true,
"archived": true,
```

[Fix] `get_circuits` archived filter

---

CHANGELOG.rst
ui/k-toolbar/main.kytos

Fixes #181, this on top of PR #208
- Added ``sb_priority`` UI component on ``k-toolbar``. (editing was already supported)
- Created an EVC with priority different than default:
```
❯ sudo ovs-ofctl -O OpenFlow13 dump-flows s1
cookie=0x0, duration=89.555s, table=0, n_packets=0, n_bytes=0, send_flow_rem priority=50000,dl_src=ee:ee:ee:ee:ee:03 actions=CONTROLLER:65535
cookie=0x0, duration=89.541s, table=0, n_packets=0, n_bytes=0, send_flow_rem priority=50000,dl_src=ee:ee:ee:ee:ee:02 actions=CONTROLLER:65535
cookie=0xaa72d3a029b7254e, duration=25.358s, table=0, n_packets=0, n_bytes=0, send_flow_rem priority=33333,in_port="s1-eth1" actions=push_vlan:0x88a8,set_field:6203->vlan_vid,output:"s1
-eth4"
cookie=0xaa72d3a029b7254e, duration=25.355s, table=0, n_packets=0, n_bytes=0, send_flow_rem …
```

[Feature/UI] sb_priority component on k-toolbar

---

CHANGELOG.rst
models/evc.py
openapi.yml
tests/unit/test_main.py

Fixes #210 
- Validated ``queue_id`` on ``POST /v2/evc`` and differentiated 0 from None.
- Created EVC with this payload locally setting queue_id as 0:
```
{
"name": "epl",
"service_level": 7,
"queue_id": 0,
"sb_priority": 2000,
"dynamic_backup_path": true,
"uni_a": {
"interface_id": "00:00:00:00:00:00:00:01:1"
},
"uni_z": {
"interface_id": "00:00:00:00:00:00:00:03:1"
}
}
```
```
❯ sudo ovs-ofctl -O OpenFlow13 dump-flows s1
cookie=0x0, duration=41.244s, table=0, n_packets=0, n_bytes=0, send_flow_rem priority=50000,dl_src=ee:ee:ee:ee:ee:03 actions=CONTROLLER:65535
cookie=0x0, duration=41.192s, table=0, n_packets=0, n_bytes=0, send_flow_rem priority=50000,dl_src=ee:ee:ee:ee:ee:02 actions=CONTROLLER:65535
cookie=0xaa32e88ccd32804e, duration=28.814s, table=0, n_packets=1, n_bytes=98, …
```

[Fix] Differentiate `queue_id` zero from `None`

---

CHANGELOG.rst
ui/k-toolbar/main.kytos

Fixes #182 
- Added ``queue_id`` UI component on ``k-toolbar``.
@rmotitsuki when you implement the UI vertical animations feel free to reorganize or move this component accordingly
- Created EVC with `queue_id: 0`:
```
❯ sudo ovs-ofctl -O OpenFlow13 dump-flows s1 cookie=0xaa00000000000001/0xff00000000000000
cookie=0xaa9b56e899c4bc4c, duration=87.027s, table=0, n_packets=1, n_bytes=70, send_flow_rem in_port="s1-eth1" actions=push_vlan:0x88a8,set_field:4428->vlan_vid,output:"s1-eth4",set_que
ue:0
cookie=0xaa9b56e899c4bc4c, duration=87.025s, table=0, n_packets=1, n_bytes=74, send_flow_rem in_port="s1-eth4",dl_vlan=332 actions=pop_vlan,output:"s1-eth1",set_queue:0
cookie=0xaa9b56e899c4bc4c, duration=86.902s, table=0, n_packets=0, n_bytes=0, send_flow_rem in_port="s1-eth3",dl_vlan=269 …
```

[Feature] UI component `queue_id` on k-toolbar

---

CHANGELOG.rst
models/evc.py

Fix #203
Before a redeploy, current flows and failover flows are removed from the switches, but the failover path was not reset to an empty making. When the `s-vlan` is marked as available, it is removed from the metadata, causing an error afterwards.
This PR uses the `remove_failover_flows` method, which also sets the path to an empty list.

[Fix]: When removing the flows for redeploy, reset failover path

---

.github/workflows/main.yml

Closes #227 
Updated GH actions to run py3.9 like scrutinizer
N/A

[fix] Updated GH actions to run py3.9

---

CHANGELOG.rst
main.py
setup.cfg
tests/unit/test_main.py

Closes #231 
- See changelog file
I repeated the same local test that caught the original issue, when sending a POST it returns 400:
```
{
"code": 400,
"description": "Could not get interface endpoint_a id 00:00:00:00:00:00:00:01:3",
"name": "Bad Request"
}
```

[Fix] Fixed EVC validation to catch nonexistent links interfaces

---

CHANGELOG.rst
main.py
models/evc.py
models/path.py
tests/unit/models/test_evc_base.py
tests/unit/models/test_path.py

Closes #230 
This PR is on top of PR #232 
- See changelog file
I also explored locally based on some cases that @italovalcy [highlighted](https://github.com/kytos-ng/mef_eline/issues/230#issuecomment-1358261774):
1 - With a ring topology, I created an EVC non dynamic path with `primary_path` between s1 and s3:
```
{
"name": "epl",
"dynamic_backup_path": false,
"uni_a": {
"interface_id": "00:00:00:00:00:00:00:01:1"
},
"uni_z": {
"interface_id": "00:00:00:00:00:00:00:03:1"
},
"primary_path": [
{
"endpoint_a": {
"id": "00:00:00:00:00:00:00:01:4"
},
"endpoint_b": {
"id": "00:00:00:00:00:00:00:03:3"
}
}
]
}
```
1.1 - I tried to set an empty `primary_path`, since `dynamic_backup_path` is `false` by default it resulted in 400:
```
{
"primary_path": []
}
```
```
{
"code": 400,
"description": …
```

[fix] update `primary_path` or `backup_path` empty

---

.github/workflows/main.yml

- Pinned tox version while kytos-ng/kytos#313 gets fixed
- Pinned tox-gh-actions following the compatibility matrix (https://pypi.org/project/tox-gh-actions/)

pinned tox version due to Issue kytos-ng/kytos#313

---

CHANGELOG.rst
main.py
tests/unit/test_main.py

Fix #239 
This is a very simple change to modify the log level of link up events, to add more information for network operators to troubleshoot issues.
- Unit tests were executed to confirm everything was okay
- Manual execution of Kytos also demonstrated the new messages were being logged successfully:
```
Jan 18 18:50:32 5003be03af14 kytos.napps.kytos/mef_eline:INFO main:648:  Event handle_link_up Link(Interface('Ampath1-eth1', 1, Switch('00:00:00:00:00:00:00:11')), Interface('Ampath2-eth1', 1, Switch('00:00:00:00:00:00:00:12')))
Jan 18 18:50:32 5003be03af14 kytos.napps.kytos/mef_eline:INFO main:648:  Event handle_link_up Link(Interface('Ampath1-eth11', 11, Switch('00:00:00:00:00:00:00:11')), Interface('Ampath4-eth11', 11, Switch('00:00:00:00:00:00:00:18')))
Jan 18 18:50:32 5003be03af14 …
```

Change log level to info for link up event

---

ui/k-info-panel/list_connections.kytos
ui/k-info-panel/show_circuit.kytos
ui/k-toolbar/main.kytos

Fix #201 
This PR add the fields of primary and secondary constraints.
The fields are included in the request of new E-Line Circuit using the accordion item, for now, without the pagination suggested.
Inside the E-line circuit detail the primary and secondary constraints fields can be visualized and updated.
Mandatory and flexible metrics are displayed in separated fields to better visualization.

Add UI primary and secondary constraints

---

models/path.py

This PR is a workaround for kytos-ng/pathfinder#37
While kytos-ng/pathfinder#37 is not fixed, this PR adds an extra procedure before requesting paths from pathfinder to increase the number of returned paths before applying `desired_links` or `undesired_links`.
Unit tests were executed and no issue was found.
Manual validation was also executed without problems:
1. Running Kytos with Amlight Mininet topoligy
2. Requesting an EVC with uni_a being 00:00:00:00:00:00:00:21:60 and uni_z being 00:00:00:00:00:00:00:16:55, also added `primary_constraints={"desired_links": ["3d8cb9eb085cf90837f49de8cdb951487936fc4fdeb3699be017c9c2701d9d6a"]}`, and `"secondary_constraints": { "undesired_links": ["21c046f5eb9fbf577701974e207c2fd2ccd8cc4b91fae77ad396924b79c48483"]}`
3. without this workaround, Kytos …

Adding workaround for pathfinder issue #37 - getting the paths when desired and undesired links are specified

---

models/evc.py
tests/unit/models/test_evc_base.py
tests/unit/models/test_evc_deploy.py
tests/unit/test_utils.py
utils.py

Fixes #245 
Leveraging the extra information provided by Sdntrace_cp from PR kytos-ng/sdntrace_cp#59, this PR adds an extra validation mechanism for intra-switch EVCs. The extra validation also helps some corner cases where the flows are inconsistent in the last hop of the forwarding process (e.g., due to an unexpected modification from other Napps or -- unlikely -- due to a flow removed).
The modifications provided by this PR are:
- Added a method to encapsulate the verification of intra-switch EVCs (`EVCBase.is_intra_switch()`) and code refactored leveraging the new method
- Refactored `EVCDeploy.check_trace()` to return a boolean to be consumed by its caller and update the list of EVCs to be checked (instead of updating the list directly)
- Added `utils.compare_uni_out_trace()` to …

Adding validation mechanism for consistency check on intra-switch EVCs

---

CHANGELOG.rst
models/evc.py
tests/unit/models/test_evc_base.py

Closes #249 
Added `uni_a` and `uni_z` to `attributes_requiring_redeploy`
Updated local test `test_expected_requiring_redeploy_attributes()` adding `uni_a` and `uni_z` to expected values.
e2e tests on PR [#201](https://github.com/kytos-ng/kytos-end-to-end-tests/pull/201)

Added UNIs to attributes_requiring_redeploy

---

CHANGELOG.rst
main.py
models/evc.py
tests/unit/test_main.py
utils.py

Closes #223 
Added these keys to the content to these events:
- Keys: `{"evc_id", "name", "metadata", "active", "enabled", "uni_a", "uni_z"}`
- Events: 
```
kytos/mef_eline.updated
kytos/mef_eline.deleted
kytos/mef_eline.(redeployed_link_(up|down)|deployed)
```
On commit [97ca90fc35edcbbbad3e6848f4e943073246eab8](https://github.com/kytos-ng/mef_eline/pull/257/commits/97ca90fc35edcbbbad3e6848f4e943073246eab8)
Added the line `print("CONTENT -> ", content)` inside `emit_event()`, here are the results for every event:
- kytos/mef_eline.created
```
2023-02-03 13:00:07,755 - WARNING [kytos.napps.kytos/mef_eline] (thread_pool_app_6) Failover path for EVC(0a7faf5523ee4d, some) was not deployed: No available path was found                             
CONTENT ->  {'evc_id': '0a7faf5523ee4d', …
```

Improved content on EVCs CRUD events

---

CHANGELOG.rst
db/models.py

Closes #265 
This PR fixes a minor typo in the persistence of the `minimum_flexible_hits` path constraints doc. The attribute was not persistent due to the incorrect name.
After testing mef_eline with the proposed change, the attribute gets persistent. The behavior observed in the Issue #265 is no longer observed:
```
{"circuit_id":"16ca6e281ddf48"}
{
"flexible_metrics": {
"bandwidth": 100,
"delay": 10,
"priority": 10,
"utilization": 0
},
"minimum_flexible_hits": 2,
"spf_attribute": "hop",
"undesired_links": [
"f84da0639233fe9d44614e6060abfa41d997b28d9ad729e8882ba4ddc02c29ed"
]
}
```
Not necessary.

fix: solves typo in minimum_flexible_hits attribute name

---

CHANGELOG.rst
ui/k-info-panel/show_circuit.kytos
ui/k-toolbar/main.kytos

Related to PR #268 and Issue #264 
This PR is similar to #268. The only difference is that it is backported to `2022.3`.
Same local tests as documented in PR #268
N/A

fix: update path constraint attribute list to add reliability attribute - backport to 2022.3

---

CHANGELOG.rst
ui/k-info-panel/show_circuit.kytos
ui/k-toolbar/main.kytos

Closes #264 
This PR adds the attribute `reliability` to the path constraint list of an EVC.
Now the creation of an EVC includes the reliability:
Also, editing an EVC include the field to provide reliability:
N/A

fix: update attribute list for path constraints to add reliability attribute

---

CHANGELOG.rst
models/evc.py
tests/unit/models/test_evc_base.py

Related to PR [#254](https://github.com/kytos-ng/mef_eline/pull/254), PR [#201](https://github.com/kytos-ng/kytos-end-to-end-tests/pull/201) and Issue [#249](https://github.com/kytos-ng/mef_eline/issues/249)
This PR is similar to [#254](https://github.com/kytos-ng/mef_eline/pull/254). The only difference is that it is backported to `2022.3`.
Same local tests as documented in PR [#254](https://github.com/kytos-ng/mef_eline/pull/254)
Same E2E tests as in PR [#254](https://github.com/kytos-ng/mef_eline/pull/254). These are in PR [#201](https://github.com/kytos-ng/kytos-end-to-end-tests/pull/201)

Added `uni_a` and `uni_z` to `attributes_requiring_redeploy` - backport to 2022.3

---

CHANGELOG.rst
models/evc.py

Closes #273 
This PR will fix an issue in which Kytos-ng is redeploying intra-switch EVCs upon receiving link_up events. Intra-switch EVCs do not depend on any links to be set up. Thus, adding an earlier return on the link-up handler for those cases makes sense.
I've repeated the same steps documented in Issue #273 and no intra-switch EVC was redeployed:
```
2023-02-14 15:02:50,835 - INFO [kytos.core.controller] [controller.py:315:start_controller] (MainThread) Starting Kytos - Kytos Controller
0
``` 
The end-to-end tests also shows that no regression was observed with the proposed changes:
```
platform linux -- Python 3.9.2, pytest-7.2.0, pluggy-1.0.0
rootdir: …
```

fix: avoid redeploy of intra-switch EVCs on link_up events

---

CHANGELOG.rst
models/evc.py

Related to PR #275, and Issue #273 
This PR is similar to #275. The only difference is that it is backported to `2022.3`.
Same local tests as documented in PR #275
Same E2E tests as in PR #275

fix: avoid redeploy of intra-switch EVCs on link_up events - backport to 2022.3

---

CHANGELOG.rst
main.py
models/evc.py
tests/unit/models/test_evc_deploy.py
tests/unit/test_utils.py
utils.py

This PR is related to [PR 75 in sdtrace_cp](https://github.com/kytos-ng/sdntrace_cp/pull/75).
Previously, for:
```
traces = EVCDeploy.run_bulk_sdntraces(uni_list)
```
The response was a dictionary where the keys were switches and the values were lists of paths.
Now the response is simpler: A list of lists (paths).
This PR updates `check_list_traces` to use the new version of `PUT /traces` from `sdntrace_cp`
Also, previously the following error was obtained:
```
File "/home/gretel/repos_kytos/env_for_kytos/var/lib/kytos/napps/kytos/mef_eline/main.py", line 99, in execute_consistency
circuits_checked = EVCDeploy.check_list_traces(circuits_to_check)
File "/home/gretel/repos_kytos/env_for_kytos/var/lib/kytos/napps/../napps/kytos/mef_eline/models/evc.py", line 1232, in check_list_traces …
```

fix: update function `check_list_traces` for consistency check with bulk traces

---

CHANGELOG.rst
kytos.json
ui/k-toolbar/main.kytos

- Backported from PR #284 
- See updated changelog file for more information
I confirmed that on `k-toolbar` the constraint options were hid as expected, and in the edit view component the optional constraint options are still available and functioning
```
"primary_constraints": {
"desired_links": [],
"mandatory_metrics": {
"ownership": "blue"
},
"spf_attribute": "hop",
"spf_max_path_cost": 100.0,
"undesired_links": []
},
```
N/A

fix: hid ui primary and secondary constraints on `k-toolbar` - backport to 2022.3

---

CHANGELOG.rst
ui/k-toolbar/main.kytos

Closes #283 
See updated changelog file (I'll send a backport to 2022.3.1 shortly)
I confirmed that on `k-toolbar` the constraint options were hid as expected, and in the edit view component the optional constraint options are still available and functioning
```
"primary_constraints": {
"desired_links": [],
"mandatory_metrics": {
"ownership": "blue"
},
"spf_attribute": "hop",
"spf_max_path_cost": 100.0,
"undesired_links": []
},
```
N/A

fix: hid ui primary and secondary constraints on ``k-toolbar`` in the meantime

---

CHANGELOG.rst
models/evc.py
tests/unit/models/test_evc_deploy.py

This is related to [PR 73 in sdntrace_cp](https://github.com/kytos-ng/sdntrace_cp/pull/73)
Update function `check_trace` for an early return in the case of invalid traces. That is, first it is checked that the traces have type `last` in their last step.
Add one unit test: `test_check_list_traces_invalid_types` to check the correct behavior for traces that do not end with `last`.
N/A
N/A

feature: Early return in `check_trace`.

---

models/evc.py
openapi.yml
tests/unit/models/test_evc_deploy.py

Closes #292 
Remove `run_sdntrace` since `run_bulk_sdntraces` is now used.
N/A
N/A

fix: Remove `run_sdntrace`

---

CHANGELOG.rst
controllers/__init__.py
main.py
models/evc.py
openapi.yml
tests/unit/test_controllers.py
tests/unit/test_main.py

Closes #225 
Added bulk updates for metadata
- A new `POST /v2/evc/metadata` for metadata bulk creation/update taking `circuit_id: List[str]` in the request body
- A new `DELETE /v2/evc/metadata/<key>` for deleting a metadata key taking `circuit_id: List[str]` in the request body`
- Augment `GET /v2/evc/` supporting to filter for a given query parameter e.g. `metadata.extra=data`
- Update bulk
API url: `POST /v2/evc/metadata`
Body request:
```
{"circuit_ids": [
"1de5a5a5ec9241",
"2c255cc263e447",
],
"First": "first data",
"Second": "data 2"}
```
- Delete bulk
API url: `DELETE /v2/evc/metadata/<key>`
Body request:
```
{
"circuit_ids": [
"1de5a5a5ec9241",
"2c255cc263e447",
"nonexistent"
],
"First": "first data""
}
```
- Get evcs
API url: `GET /v2/evc?metadata.Test=123`
In progress

Added bulk api requests

---

CHANGELOG.rst
main.py
requirements/dev.txt
requirements/run.in
requirements/run.txt
utils.py

Related and depends on https://github.com/kytos-ng/kytos/pull/352
- Tried to create an invalid circuit
```
{
"code": 400,
"description": "The request body contains invalid API data. 1 is not of type 'string' for field uni_a/interface_id.",
"name": "Bad Request"
}
```
- Also created a valid circuit:
```
{
"circuit_id": "760f1c9135264d"
}
```
Reran https://github.com/kytos-ng/kytos-end-to-end-tests/pull/218 using this branch with `kytos` branch `feat/openapi_decorator` selecting these two relevant tests:
```
+ python3 -m pytest tests/ -k test_026_validate_bad_request_response_format
platform linux -- Python 3.9.2, pytest-6.2.5, py-1.11.0, pluggy-1.0.0
plugins: …
```

chore: replaced `@validate` with `@validate_openapi` from `kytos.core.helpers`

---

settings.py

Related to [PR of sdntrace_cp](https://github.com/kytos-ng/sdntrace_cp/pull/93)
Add `v1` on routes of `sdntrace_cp`
I made sure `/traces` is called correctly:
```
2023-04-11 19:12:15,082 - INFO [kytos.napps.kytos/mef_eline] (mef_eline) EVC(6875c026f20a4b, epl) was deployed.
2023-04-11 19:12:15,083 - INFO [kytos.napps.kytos/mef_eline] (mef_eline) EVC(5b1147f173c84a, epl) enabled but inactive - redeploy
```
N/A

feature: Update `v1` on routes of `sdntrace_cp`

---

CHANGELOG.rst
main.py
models/evc.py
openapi.yml

Closes #291 
Closes #306
Updated `openapi.yml` to be used by the endpoints:
```
@rest("/v2/evc/<circuit_id>", methods=["PATCH"])
@rest("/v2/evc/schedule/", methods=["POST"])
@rest("/v2/evc/schedule/<schedule_id>", methods=["PATCH"])
```
Use the rest endpoints listed before to test results. Also ran unit tests which covers error codes.
```
tests/test_e2e_10_mef_eline.py ..........ss.....x.....x................  [ 26%]
tests/test_e2e_11_mef_eline.py ......                                    [ 29%]
tests/test_e2e_12_mef_eline.py .....xx.                                  [ 32%]
tests/test_e2e_13_mef_eline.py …
```

Update openapi to be used by requests

---

tests/unit/test_utils.py
utils.py

Fixes #308 
Create a function to split a vlan range into the minimum number of possible vlan/mask pairs.
At each step, finds the maximum power of 2 that divides the first remaining tag of the range, without going beyond the end of the range.

feat: Utility function to split a vlan range

---

models/evc.py

Related to [PR in `sdntrace_cp`](https://github.com/kytos-ng/sdntrace_cp/pull/95)
Catch `Timeout` exception instead of `ConnectTimeout` on requests to `/traces`. 
See [PR](https://github.com/kytos-ng/sdntrace_cp/pull/95)

catch Timeout error on request for /traces

---

db/models.py
models/path.py
openapi.yml
settings.py
tests/unit/models/test_path.py
ui/k-info-panel/show_circuit.kytos
ui/k-toolbar/main.kytos

Closes #296
This depends on https://github.com/kytos-ng/pathfinder/pull/47
- Provisioned an EPL and also double checked it was correctly displayed in the UI
```
platform linux -- Python 3.9.2, pytest-7.2.0, pluggy-1.0.0
rootdir: /builds/amlight/kytos-end-to-end-tester/kytos-end-to-end-tests
plugins: rerunfailures-10.2, timeout-2.1.0, anyio-3.6.2
collected 227 items
tests/test_e2e_10_mef_eline.py ..........ss.....x.....x................  [ 26%]
tests/test_e2e_11_mef_eline.py ...... …
```

fix: removed support for `desired_links` on path constraints and reverted pathfinder#37 workaround

---

CHANGELOG.rst
openapi.yml
ui/k-info-panel/show_circuit.kytos

Fixes #315
Check constraint field values while building the payload. It should remove empty constraint attributes.
The following attributes´ default values: bandwidth, service_level were set to 0, and sb_priority and queue were set to null, as the API spec validation requires to be integer.
Select the Mef-Eline item
Click the button "List Installed EVC"
Choose an EVC
- Leave the Southbound priority, Bandwidth, Queue, Service level with empty values and save.
- Change the values Southbound priority, Bandwidth, Queue, Service level and save.

Fix not nullable value for constraint fields

---

CHANGELOG.rst
exceptions.py
main.py
models/evc.py
tests/unit/test_main.py
tests/unit/test_utils.py
utils.py

Closes #317 
Updated creation of a circuit to not allowed for a intra-switch EVC when the used switch status is `DISABLED`
Tried to create an EVC:
```
{
"name": "Intra-EVC",
"dynamic_backup_path": true,
"uni_a": {
"tag": {"value": 101, "tag_type": 1},
"interface_id": "00:00:00:00:00:00:00:02:2"
},
"uni_z": {
"tag": {"value": 101, "tag_type": 1},
"interface_id": "00:00:00:00:00:00:00:02:1"
}
}
```
```
platform linux -- Python 3.9.2, pytest-7.2.0, pluggy-1.0.0
collected 232 items …
```

Added if statement for disabled intra EVC switch

---

CHANGELOG.rst
models/evc.py
models/path.py
tests/unit/models/test_evc_deploy.py
tests/unit/models/test_path.py

Related to kytos PR [#221](https://github.com/kytos-ng/kytos/pull/329)
Adapting `path` and `EVCDeploy` to ordered endpoints from kytos PR. Endpoints are chosen  depending on first/previous switch which is usually `uni_a` switch.
Installing EVCs and disabling links
```
platform linux -- Python 3.9.2, pytest-7.2.0, pluggy-1.0.0
collected 232 items
tests/test_e2e_10_mef_eline.py ..........ss.....x.....x.RRFRRF.......... [ 24%]
... …
```

Fixed issues with ordered endpoints

---

CHANGELOG.rst
ui/k-info-panel/list_connections.kytos

**Closes** #331 
Update EVC list to sort VLAN A and VLAN Z fields to acts as number.
Test VLAN A and VLAN Z sort with ascending and descending order.
Test input field to filter the list with partial VLAN values

Fix UI EVC list to sort VLAN as number

---

CHANGELOG.rst
controllers/__init__.py
db/models.py
models/evc.py
tests/unit/models/test_evc_base.py
tests/unit/test_db_models.py
tests/unit/test_main.py
ui/k-info-panel/show_circuit.kytos

Closes #347 
Redeployment was based on the field value. Changed to always be `True`
Added unit test with issue case.
Patched EVC with `{"queue_id":null}`

Fixed unset queue with null

---

CHANGELOG.rst
db/models.py
models/path.py
openapi.yml
scripts/002_unset_spf_attribute.py
scripts/README.md
settings.py
tests/unit/models/test_path.py
tests/unit/test_main.py
ui/k-info-panel/show_circuit.kytos
ui/k-toolbar/main.kytos

Closes #351 
This PR supersedes PR #352, due to a new requirement implementation detail 
I'll send a backport for 2022.3 shortly
I ran the following tests:
- Created a new EVC via the UI using the `default` spf_attribute, confirming that it wouldn't set it as expected
- Updated an EVC in the UI, changed to a non default value and changed back again to default, and it only set the attr when it was non default in the request to mef_eline
- I executed the DB scripts with EVCs that still had `primary_constraints.spf_attribute = "hop"` to confirm the script would run correctly
```
rs0 [direct: primary] napps> db.evcs.find({}, {"primary_constraints": 1, "secondary_constraints": 1})
[
{
_id: '065c4df04a9244',
primary_constraints: {
spf_max_path_cost: 10, …
```

feat: exposed default `SPF_ATTRIBUTE` on settings.py

---

models/evc.py
tests/unit/models/test_evc_deploy.py

Related to [issue 102](https://github.com/kytos-ng/sdntrace_cp/issues/102)
`type==last` is not checked anymore in `check_trace`.
See [related PR in `sdntrace_cp`](https://github.com/kytos-ng/sdntrace_cp/pull/106)
In progress.

Remove the early return with `type==last`

---

CHANGELOG.rst

Due to lack of remote write permission on PR #360, I had to open this new PR to update changelog
```
2023-08-29 16:25:20,533 - INFO [uvicorn.access] (MainThread) 127.0.0.1:36898 - "PATCH /api/kytos/mef_eline/v2/evc/e511f8c9068546/redeploy HTTP/1.1" 202
```

chore: updated changelog for pr 360

---

CHANGELOG.rst
main.py
models/evc.py
tests/unit/models/test_link_protection.py
tests/unit/test_main.py

Closes #338 
Added listener for `kytos/topology.updated` for recent disabled interfaces
Added new condition to circuit consistency to additionally check for interfaces
Create an EVC and disable the interface of one of the UNIs
Check if consistency check enables the previous EVC only when its interfaces have been enabled
Teste with 400 EVCs with `uni_a` interface `00:00:00:00:00:00:00:01:1`
Activating and deactivating interface `00:00:00:00:00:00:00:01:1` in intervals of 5 seconds yields these results:
MongoDB:
Kytos Transactions:
Kytos dependency:

Handled disabled UNI

---

CHANGELOG.rst
main.py
models/evc.py
tests/unit/test_main.py

Closes #374 
I simulated the multiple failures described in Issue #374, and repeated the test multiple times. No further error, misbehavior, or race condition was identified.
Script to run the simulation:
```
root@3b9f1397364f:/# for vlan in $(seq 101 101); do curl -H 'Content-type: application/json' -X POST http://127.0.0.1:8181/api/kytos/mef_eline/v2/evc/ -d '{"name": "evc-vlan-'$vlan'", "dynamic_backup_path": true,  "uni_z": {"tag": {"value": '$vlan', "tag_type": 1}, "interface_id": "00:00:00:00:00:00:00:01:1"}, "uni_a": {"tag": {"value": '$vlan', "tag_type": 1}, "interface_id": "00:00:00:00:00:00:00:03:1"}}'; done
root@3b9f1397364f:/# cat /mydata2/run-test-failover.sh
for i in $(seq 1 20); do
echo "--------" $i $(date);
tmux send-keys -t mn "sh ip link set …
```

Prevent race conditions in failover_path

---

CHANGELOG.rst
README.rst
kytos.json
main.py
models/evc.py
tests/unit/models/test_evc_base.py
tests/unit/test_main.py
utils.py

Closes #380
This PR needs update on `topology` [PR](https://github.com/kytos-ng/topology/pull/169)
Based on `2023.1.1`
When an EVC is created, updated, or deleted, its UNI tag is now removed and/or added to `uni.interface.available_tags`
Created, updated, and deleted EVCs.
Tried the previous actions with conflicting TAGs to check on error messages.
```
platform linux -- Python 3.9.2, pytest-7.2.0, pluggy-1.3.0
collected 242 items
tests/test_e2e_10_mef_eline.py …
```

backport 2023.1.2: Allocating UNI tags

---

CHANGELOG.rst
models/evc.py
scripts/README.md
scripts/redeploy_evpls_same_vlans.py
tests/unit/models/test_evc_deploy.py

Closes #389 
- See updated changelog
- See updated scripts/README.md
I created an inter evpl with same vlans on UNI A and Z and confirmed the expected flows and that sdntrace_cp and sdntrace were still tracing as expected:
```
cookie=0xaaa73f765873d841, duration=12.858s, table=0, n_packets=0, n_bytes=0, send_flow_rem priority=20000,in_port="s3-eth1",dl_vlan=101 actions=set_field:4197->vlan_vid,push_vlan:0x88a8,set_field:4097->vlan_vid,output:"s3-eth3"
```
```
{
"flow": {
"owner": "mef_eline",
"cookie": 12271464045111059785,
"match": {
"in_port": 1,
"dl_vlan": 101
},
"actions": [
{
"action_type": "set_vlan",
"vlan_id": 101
},
{
"action_type": "push_vlan",
"tag_type": "s"
},
{
"action_type": "set_vlan",
"vlan_id": 1
},
{
"action_type": "output",
"port": 4
}
],
"table_id": 0,
"table_group": …
```

feat: add `set_vlan` only if UNI A vlan and UNI z vlan are different.

---

CHANGELOG.rst
kytos.json
models/evc.py
scripts/README.md
scripts/redeploy_evpls_same_vlans.py
tests/unit/models/test_evc_deploy.py

Closes #391 
Backporting https://github.com/kytos-ng/mef_eline/pull/390 to `2023.1.3`. and bumping the version. 
Local tests and e2e tests were run in the original linked PR.

[backport release 2023.1.3] feat: add `set_vlan` only if UNI A vlan and UNI z vlan are different

---

CHANGELOG.rst
main.py
models/evc.py
tests/unit/models/test_link_protection.py
tests/unit/test_main.py

Closes #365, closes #218
This PR does the following:
- Prevent Link up events from rerouting active EVCs
- Prevents EVCs from being rerouted on startup due to automatically deactivating the EVC
Playing around with this, I found that disconnecting a switch from kytos between resets, would no longer result in EVCs being rerouted, which from discussions with @italovalcy, and @viniarck is the desired behaviour. Previously, if a switch did not reconnect during startup, an EVC which used that switch was likely to be rerouted.
Here are the E2E test results. I had accidentally ran the E2E tests without the patch applied, but got the same results before and after applying the patch.
```
kytos-end-to-end-tests-kytos-1  | Starting enhanced syslogd: rsyslogd.
kytos-end-to-end-tests-kytos-1  | …
```

Stable EVCs

---

CHANGELOG.rst
README.rst
main.py
tests/unit/test_main.py

Closes #400 
- Subscribed to it on `telemetry_int` and confirmed EVCs got published:
```
2023-11-14 16:27:39,451 - INFO [kytos.napps.kytos/telemetry_int] [main.py:208:on_mef_eline_evcs_loaded] (MainThread) got evcs_loaded {'4ba2a0bd562c4e': {'active': False, 'archived': Fals
e, 'backup_path': [], 'bandwidth': 0, 'circuit_scheduler': [], 'current_path': [], 'dynamic_backup_path': True, 'enabled': True, 'failover_path': [], 'id': '4ba2a0bd562c4e', 'metadata': 
{}, 'name': 'inter_evpl', 'primary_path': [], 'service_level': 6, 'uni_a': {'tag': {'tag_type': 'vlan', 'value': 301}, 'interface_id': '00:00:00:00:00:00:00:01:1'}, 'uni_z': {'tag': {'ta
g_type': 'vlan', 'value': 302}, 'interface_id': '00:00:00:00:00:00:00:03:1'}, 'sb_priority': None, 'execution_rounds': 0, …
```

feat: published `kytos/mef_eline.evcs_loaded` when loading evcs during setup

---

CHANGELOG.rst
main.py
models/evc.py
requirements/dev.in
tests/unit/models/test_evc_base.py
tests/unit/test_main.py

Closes #404 
Events for vlan usage now include special vlans "untagged" and "any
Related kytos [PR](https://github.com/kytos-ng/kytos/pull/431)
Tested with UI and API requests. Created, deleted, modified EVCs.
```
platform linux -- Python 3.9.2, pytest-7.2.0, pluggy-1.3.0
collected 244 items
tests/test_e2e_10_mef_eline.py ..........ss.....x.....x................  [ 24%]
tests/test_e2e_11_mef_eline.py ......                                    [ 27%]
tests/test_e2e_12_mef_eline.py …
```

Added special vlans to Interface events.

---

exceptions.py
main.py
models/evc.py
tests/unit/models/test_evc_base.py
tests/unit/test_main.py

Closes #410 
Added `_check_no_tag_duplication()` to check for no tag UNIs when necessary
Added `check_no_tag_duplicate()` to check for no tag UNIs with current EVC
Update and create circuits with duplications
```
platform linux -- Python 3.9.2, pytest-7.2.0, pluggy-1.3.0
collected 244 items
tests/test_e2e_10_mef_eline.py ..........ss.....x.....x................  [ 24%]
tests/test_e2e_11_mef_eline.py ......                                    [ 27%]
tests/test_e2e_12_mef_eline.py …
```

fix: Look for not tag UNI duplication

---

CHANGELOG.rst
models/evc.py
tests/unit/models/test_evc_deploy.py

Closes #366
Enhanced log by adding EVC ID and name to the log
`
2023-12-05 10:58:33,582 - WARNING [kytos.napps.kytos/mef_eline] (mef_eline) From EVC(4781ad8f491444) named 'EVC_2'. Invalid trace from uni_a: [{'dpid': '00:00:00:00:00:00:00:01', 'port': 1, 'time': '2023-12-05 10:58:33.578736', 'type': 'starting', 'vlan': 100}, {'dpid': '00:00:00:00:00:00:00:02', 'port': 2, 'time': '2023-12-05 10:58:33.578789', 'type': 'last', 'vlan': 1, 'out': {'port': 1, 'vlan': 100}}]
`
Update uni test
Forcing invalid trace and consistency check

Improved log for invalid trace

---

CHANGELOG.rst
models/evc.py
tests/unit/models/test_evc_deploy.py

Closes https://github.com/kytos-ng/sdntrace_cp/issues/109
Created two EVPLs with 'uni_a' and 'uni_z', "inter_evpl" had 'uni_a' and 'uni_z' inverted compared to the expected current_path as @italovalcy has caught on the original issue, then I reran all the checks and they succeeded:
```
❯ curl -H 'Content-type: application/json' -X POST http://127.0.0.1:8181/api/kytos/mef_eline/v2/evc/ -d '{"name": "inter_evpl", "dynamic_backup_path": true, "uni_z": {"interface_id": "00:00:00:00:00:00:00:01:1", "tag": {"tag_type": 1, "value": 2222}}, "uni_a": { "interface_id": "00:00:00:00:00:00:00:03:1", "tag": {"tag_type": 1, "value": 2222}}}'
{"circuit_id":"fc98ecc9f0194a"}
❯ curl -H 'Content-type: application/json' -X POST http://127.0.0.1:8181/api/kytos/mef_eline/v2/evc/ -d …
```

fix: sdntrace_cp check_trace `current_path` comparison with the expected UNI order

---

CHANGELOG.rst
openapi.yml
tests/unit/test_main.py

Closes #368 
I went ahead and ended up fixing this since for `telemetry_int` it was getting in the way sometimes.
```
❯  echo '{ "some_key": "some_value", "circuit_ids": [] }' | http POST http://127.0.0.1:8181/api/kytos/mef_eline/v2/evc/metadata
HTTP/1.1 400 Bad Request
content-length: 111
content-type: application/json
date: Tue, 05 Dec 2023 18:03:27 GMT
server: uvicorn
{
"code": 400,
"description": "The request body contains invalid API data. [] is too short for field circuit_ids."
}
❯  echo '{ "some_key": "some_value", "circuit_ids": [1] }' | http POST http://127.0.0.1:8181/api/kytos/mef_eline/v2/evc/metadata
HTTP/1.1 400 Bad Request
content-length: 123
content-type: application/json
date: Tue, 05 Dec 2023 18:03:39 GMT
server: uvicorn
{
"code": 400, …
```

fix: required at least one circuit_id on `POST v2/evc/metadata`

---

CHANGELOG.rst
main.py
models/evc.py
tests/unit/models/test_link_protection.py
tests/unit/test_main.py

Closes #398 
Closes #416 
Added if statement when an EVC is inactive, enabled and needs to be redeployed
Performed the test from the issue
```
platform linux -- Python 3.9.2, pytest-7.2.0, pluggy-1.3.0
plugins: rerunfailures-10.2, timeout-2.1.0, anyio-3.6.2
collected 254 items
tests/test_e2e_10_mef_eline.py ..........ss.....x.....x................  [ 23%]
tests/test_e2e_11_mef_eline.py ......                                    [ 25%]
tests/test_e2e_12_mef_eline.py .....Xx.                                  [ 29%] …
```

Redploying when updating an enabled EVC

---

CHANGELOG.rst
models/path.py
tests/unit/models/test_path.py

Closes #417 (I went ahead fixed it, since I had the scenario already available)
Same as the one reported in the issue, now it no longer crashes:
```
kytos $> 2023-12-13 11:13:42,914 - INFO [kytos.napps.kytos/flow_manager] [utils.py:196:flows_to_log_info] (AnyIO worker thread) Send FlowMod from request dpid: 00:00:00:00:00:00:00:03, 
command: delete, force: True,  flows[0, 1]: [{'cookie': 12254910601279224650, 'cookie_mask': 18446744073709551615}]
2023-12-13 11:13:42,916 - INFO [uvicorn.access] [httptools_impl.py:506:send] (MainThread) 127.0.0.1:59562 - "POST /api/kytos/flow_manager/v2/delete/00%3A00%3A00%3A00%3A00%3A00%3A00%3A03
HTTP/1.1" 202
2023-12-13 11:13:42,922 - INFO [kytos.napps.kytos/flow_manager] [utils.py:196:flows_to_log_info] (AnyIO worker thread) …
```

fixed: fixed `DynamicPathManager.get_paths` return value when pathfinder returns a request error

---

CHANGELOG.rst
db/models.py
kytos.json

Add in support for not_ownership to the `PathConstraints` model on the db. This is necessary for using `not_ownership` with `mef_eline`.

Add in support for not_ownership for 2023.1.4

---

CHANGELOG.rst
main.py
tests/unit/test_main.py
utils.py

Closes #402 
Related to https://github.com/kytos-ng/kytos/pull/429
- Loaded this NApp and created an EVC 
- This had already been tested on the linked PR (but I hadn't opened this PR yet)

fix: parametrized timeout=1 when publishing KytosEvent during setup

---

CHANGELOG.rst
db/models.py
openapi.yml
tests/unit/test_db_models.py

Add in support for not_ownership to the `PathConstraints` model on the db. This is necessary for using `not_ownership` with `mef_eline`.

Add in support for not_ownership

---

CHANGELOG.rst
main.py
settings.py
tests/unit/test_main.py

Close #373
Set a timer to reduce load to database.
The timer will stop first event, while updating last received interface event. When timer ends, the last event will be applied.
Example in used:
```
2024-01-30 07:20:56,482 - WARNING [kytos.napps.kytos/mef_eline] (thread_pool_sb_155) TIMING -> 00:00:00:00:00:00:00:02:3 -> kytos/of_core.switch.interface.link_down            <----- Start time here for 02:3
2024-01-30 07:20:56,487 - WARNING [kytos.napps.kytos/mef_eline] (thread_pool_sb_130) RETURN -> 00:00:00:00:00:00:00:02:3 -> kytos/of_core.switch.interface.link_up
2024-01-30 07:20:56,487 - WARNING [kytos.napps.kytos/mef_eline] (thread_pool_sb_14) TIMING -> 00:00:00:00:00:00:00:01:4 -> kytos/of_core.switch.interface.link_down             <----- Start time here for 01:4
2024-01-30 …
```

Set timer to reduce load

---

CHANGELOG.rst
models/path.py
tests/helpers.py
tests/unit/models/test_path.py

Closes #392 
Switches are taken into account when calculating `disjointness` percentage. Switches have the same values as links.
Used this [topology](https://github.com/Alopalao/Alopalao_miscellaneous/blob/main/topologies/min3.py).
Created EVC:
```
{
"name": "EVC SW2",
"dynamic_backup_path": true,
"uni_a": {
"tag": {"value": 200, "tag_type": 1},
"interface_id": "00:00:00:00:00:00:00:01:1"
},
"uni_z": {
"tag": {"value": 200, "tag_type": 1},
"interface_id": "00:00:00:00:00:00:00:03:1"
}
}
```
Printed paths from `models/path.py` line 254. Paths were reordered correctly
To be added

Adding switches to disjointedness algorithm

---

models/path.py
tests/unit/models/test_path.py

Closes #429 
For EVC paths with 1 link there are no unwanted switches. For an early return we can trust only in unwanted links
Sames as E2E [test](https://github.com/kytos-ng/kytos-end-to-end-tests/blob/31269c42a6ace8f8199f6cc3893fd8fbcd396289/tests/test_e2e_10_mef_eline.py#L150-L211)
```
+ python3 -m pytest tests/ -k test_020_create_evc_inter_switch --reruns 0 -r fEr
platform linux -- Python 3.9.2, pytest-7.2.0, pluggy-1.4.0
collected 257 items / 256 deselected / 1 selected
tests/test_e2e_10_mef_eline.py .                                         [100%]
```
```
+ python3 -m pytest tests/ --reruns 0 -r fEr
============================= …
```

Fixed early return

---

CHANGELOG.rst
main.py
models/evc.py
tests/unit/test_main.py

Closes #369
Removed archived evcs from `self.circuits`.
Tested `link_down` and `link_up` events.
Tried to delete, patch a deleted EVC.
Tried to create an schedule for a deleted EVC.
```
platform linux -- Python 3.9.2, pytest-7.2.0, pluggy-1.4.0
collected 257 items
tests/test_e2e_01_kytos_startup.py RRF.                                  [  0%]
tests/test_e2e_05_topology.py ....................                       [  8%]
tests/test_e2e_10_mef_eline.py ..........ss.....x.....x................  [ 24%]
tests/test_e2e_11_mef_eline.py ......                                    [ 26%] …
```

Removed archived evcs from `self.circuits`

---

controllers/__init__.py
main.py
models/evc.py
tests/unit/test_controllers.py
tests/unit/test_main.py

Closes #405
See updated changelog file and/or add any other summarized helpful information for reviewers (in fact, the changelog already mentions a fix similar to this one _fixed race condition in ``failover_path`` when handling simultaneous Link Down events leading to inconsistencies on some EVC_)
Using the topology presented on the issue, I executed tests with and without this change to evaluate how a user (EVC service) would be impacted. Tests consist basically of all nodes pinging to h1 (h2-h1, h3-h1, h4-h1, and h5-h1), and on each step, we disable both interfaces that directly connect the nodes (first disabling h1-h2 links; then h1-h3 links, then h1-h4 links). The link-down event is simulated around 25% of the data transfer on each step. The metric used here was the packet loss, so 0 …

Enhance link down handler to avoid race conditions in the failover path

---

CHANGELOG.rst
README.rst
models/evc.py
tests/unit/models/test_link_protection.py

Closes #454 
Local tests were documented on https://github.com/kytos-ng/telemetry_int/pull/91
No needed for this case since it doesn't impact on any existing one, and telemetry_int doesn't have e2e tests yet.

feat: added kytos/mef_eline.uni_active_updated event

---

CHANGELOG.rst
README.rst
tests/unit/test_main.py
utils.py

Closes #462 
Exercised some of the events with telemetry_int:
```
kytos $> 2024-05-16 13:49:27,329 - INFO [kytos.napps.kytos/mef_eline] (AnyIO worker thread) Removing EVC(df66e1705b1849, epl)
2024-05-16 13:49:27,332 - INFO [kytos.napps.kytos/flow_manager] (AnyIO worker thread) Send FlowMod from request dpid: 00:00:00:00:00:00:00:03, command: delete, force: True,  flows[0, 1
]: [{'cookie': 12312673024692918345, 'cookie_mask': 18446744073709551615}]
2024-05-16 13:49:27,338 - INFO [uvicorn.access] (MainThread) 127.0.0.1:41726 - "POST /api/kytos/flow_manager/v2/delete/00%3A00%3A00%3A00%3A00%3A00%3A00%3A03 HTTP/1.1" 202
2024-05-16 13:49:27,344 - INFO [kytos.napps.kytos/flow_manager] (AnyIO worker thread) Send FlowMod from request dpid: 00:00:00:00:00:00:00:01, …
```

chore: included id on `map_evc_event_content` to normalize the content

---

CHANGELOG.rst
models/path.py
tests/unit/models/test_path.py

Closes #464 
- **Without this fix**, one request will be sent for each `Path` instance `status` access:
```
kytos $> for evc in controller.napps[('kytos', 'mef_eline')].circuits.values():
...:     for i in range(10):
...:         print(evc.current_path.status)
...: 
EntityStatus.UP
2024-05-23 09:06:33,221 - INFO [uvicorn.access] (MainThread) 127.0.0.1:33264 - "GET /api/kytos/topology/v3/links HTTP/1.1" 200
2024-05-23 09:06:33,223 - INFO [uvicorn.access] (MainThread) 127.0.0.1:33280 - "GET /api/kytos/topology/v3/links HTTP/1.1" 200
EntityStatus.UP
2024-05-23 09:06:33,225 - INFO [uvicorn.access] (MainThread) 127.0.0.1:33296 - "GET /api/kytos/topology/v3/links HTTP/1.1" 200
EntityStatus.UP
2024-05-23 09:06:33,228 - INFO [uvicorn.access] (MainThread) …
```

fix: optimized `Path.status` not to depend on a HTTP request

---

CHANGELOG.rst
kytos.json
models/path.py

Closes #466 
Backport from PR #465 
- Unit tests weren't included since it's not run in the CI for backports (but see the associated PR)
Done on PR #465 
Done on PR #465

backport/fix 2023.2.1: optimized Path.status not to depend on a HTTP request

---

CHANGELOG.rst
models/evc.py
tests/unit/models/test_link_protection.py

Closes #468 
Only redeploy when handling ``kytos/topology.link_up`` if a dynamic EVC isn't active
- Created a dynamic EVC exercised link_up, it didn't redeploy after a controller restart
- Simulated link_up with this EVC active, it didn't reploy as expected
- Shut it down all NNIs interfaces, in the next link_up the link_up resulted in reploy 
```
2024-06-06 14:12:49,486 - INFO [kytos.napps.kytos/mef_eline] (thread_pool_sb_5) Event handle_interface_link_down Interface('s1-eth4', 4, Switch('00:00:00:00:00:00:00:01'))
2024-06-06 14:12:49,487 - INFO [kytos.napps.kytos/mef_eline] (thread_pool_sb_23) Event handle_interface_link_down Interface('s3-eth3', 3, Switch('00:00:00:00:00:00:00:03'))
kytos $> 
kytos $> 
kytos $> 2024-06-06 14:12:54,378 - INFO [kytos.napps.kytos/of_core] (MainThread) …
```

fix: only redeploy when handling kytos/topology.link_up if a dynamic EVC isn't active

---

CHANGELOG.rst
kytos.json
models/evc.py

Closes #469 
Backported from https://github.com/kytos-ng/mef_eline/pull/471/
Same as PR 471
Same as PR 471

[backport 2023.2.2] fix: only redeploy when handling kytos/topology.link_up if a dynamic EVC isn't active

---

CHANGELOG.rst
README.rst
main.py
models/evc.py
tests/unit/models/test_evc_deploy.py
tests/unit/test_main.py
tests/unit/test_utils.py
utils.py

Closes #456
Closes #455
This is on top of PR #471 
- Some methods which didn't return anything now also return the generated flows
I tested out in the NoviFlow lab, it's working, I'll publish the rest of the local tests on https://github.com/kytos-ng/telemetry_int/issues/90.
I've dispatched an e2e exec with this branch:
```
rootdir: /builds/amlight/kytos-end-to-end-tester/kytos-end-to-end-tests
collected 263 items
tests/test_e2e_05_topology.py …
```

feat: new failover_path publish events

---

models/evc.py
openapi.yml
tests/unit/models/test_evc_base.py

Closes #477 
No longer accepting 0 as VLAN.
Improved API docs for TAGs
Tried to create/update an EVC with VLAN 0
N/A

Removed unnecessary if statement

---

CHANGELOG.rst
ui/k-toolbar/main.kytos

Closes #180 
Closes #382 
This PR is on top of PR #473 
- Even if `telemetry_int` isn't installed this won't create any issue, since it's just setting a metadata value, which `telemetry_int` subscribes to. 
- UI with the checkbox checked (it set the metadata to request INT accordingly):
```
2024-06-12 10:27:51,472 - INFO [kytos.napps.kytos/mef_eline] (AnyIO worker thread) EVC(3e68dd8231a646, inter_evpl) was deployed.
2024-06-12 10:27:51,472 - INFO [uvicorn.access] (MainThread) 127.0.0.1:52180 - "POST /api/kytos/mef_eline/v2/evc/ HTTP/1.1" 201
2024-06-12 10:27:51,472 - INFO [kytos.napps.kytos/telemetry_int] (MainThread) Handling mef_eline.deployed on EVC id: 3e68dd8231a646
2024-06-12 10:27:51,473 - INFO [kytos.napps.kytos/telemetry_int] (MainThread) Enabling …
```

feat: UI checkbox to request that In-band Network Telemetry (INT) gets enabled

---

CHANGELOG.rst
main.py
setup.py
tests/unit/test_main.py

Closes #478 
Duplicated EVCs could happen. How?:
So these are the LOG messages from an EVC which got deployed by consistency check:
```
(mef_eline) Got circuits for check number: 3
(AnyIO worker thread) EVC(4b3cd9f35d6243, evc1) was deployed.
(AnyIO worker thread) delete_circuit /v2/evc/4b3cd9f35d6243 last CONSIS: 3          # EVC removed from memory (.pop())
(AnyIO worker thread) Removing EVC(4b3cd9f35d6243, evc1)
(mef_eline) Got circuits for check number: 4                                        # Copy EVCs from memory and DB 
(thread_pool_app_0) Failover path for EVC(4b3cd9f35d6243, evc1) was deployed.
(AnyIO worker thread) EVC removed. EVC(4b3cd9f35d6243, evc1)                        # Confirmation EVC deleted removed DB
127.0.0.1:55234 - "DELETE …
```

Added lock for EVC deletion

---

CHANGELOG.rst
models/evc.py
tests/unit/models/test_evc_deploy.py

Closes #481
Catching error messages from `KytosNoTagAvailableError` for a better log message when a path failed to be deployed. Example: 
`Failover path for EVC(d19049313a3341, evc-111) was not deployed: No available path was found. 1 path was rejected with message: ['Link 78282c4d5b579265f04ebadc4405ca1b49628eb1d684bb45e5d0607fa8b713d0 has no vlan available.']`
Deployed EVC with no available VLANs in the possible path interfaces
N/A

Show error messages from deploying path tries

---

CHANGELOG.rst
ui/k-info-panel/list_connections.kytos

Closes #452
Cause: The operation `$.ajax()` is asynchronous. We have one asynchronous call in each `loadDpidNames()` and `listEVCs()`. `loadDpidNames()` gets `node_name` from the switches. Thus if `listEVCs()` starts before, the switches will show their dpid instead of their `node_name`.
Added `Promise` to wait for `loadDpidNames()` to finish its process and `listEVCs()` is guaranteed to work with `node_name` if there is any.
Added a `time.wait(self.extra)` in the api call [method](https://github.com/kytos-ng/topology/blob/d9395127f624dd9b269d9f4c8a2237baef547787/main.py#L266) for switches in `topology` NApp.
N/A

Set an order for ajax

---

CHANGELOG.rst
main.py
settings.py
tests/unit/test_main.py

Closes #372
Removes client side batching.
Everything seems to work fine with creating EVCs.
Will have to run these tests later.

Remove Client Side Batching

---

CHANGELOG.rst
kytos.json
main.py
models/evc.py
tests/unit/models/test_evc_deploy.py
tests/unit/test_main.py
tests/unit/test_utils.py
ui/k-info-panel/show_circuit.kytos
utils.py

Closes #496
Closes #489 
Corrected flow deletion for `old_paths` which was sending incorrect flows.
Replicate issue
Created e2e test [PR](https://github.com/kytos-ng/kytos-end-to-end-tests/pull/323) to test this PR.
```
collected 267 items
tests/test_e2e_06_topology.py ....                                       [  8%]
tests/test_e2e_10_mef_eline.py …
```

Corrected wrong flow_mod sent to deletion

---

CHANGELOG.rst
kytos.json
main.py
models/evc.py
models/path.py
tests/unit/models/test_path.py

Closes #501
Flows sent through events were not copies and any modification would affect any NApp listening to the event.
Added listener for the events that sent flows to verify any modifications to flows were not affecting other listeners.
N/A

Events with flows are deep copied

---

CHANGELOG.rst
kytos.json
main.py
tests/unit/test_main.py

Closes #504 
I'm still analyzing other potential related one https://github.com/kytos-ng/telemetry_int/issues/133 though
- Simulated/forced `failover_old_path` events, it no longer is sending extra removed flows
```
2024-09-03 11:30:31,266 - INFO [kytos.napps.kytos/flow_manager] (thread_pool_app_24) Send FlowMod from KytosEvent dpid: 00:00:00:00:00:00:00:01, command: delete, force: True, total_len
gth: 101,  flows[0, 101]: [{'cookie': 12285320825246548803, 'match': {'in_port': 2, 'dl_vlan': 1}, 'owner': 'mef_eline', 'cookie_mask': 18446744073709551615}, {'cookie': 12254970944063
612495, 'match': {'in_port': 2, 'dl_vlan': 3}, 'owner': 'mef_eline', 'cookie_mask': 18446744073709551615}, {'cookie': 12316423280674281796, 'match': {'in_port': 2, 'dl_vlan': 7}, 'owne …
```

hotfix 2024.1.3: fixed extra removed flows that were being published on event ``"failover_old_path"``

---

CHANGELOG.rst
kytos.json
models/path.py
tests/unit/models/test_path.py

Closes #489
Added `httpx.ConnectError` to be caught and trigger a retry
Created an EVC that cannot have a failover path so when kytos is starting a path search is triggered
```
collected 267 items
tests/test_e2e_06_topology.py ....                                       [  8%]
tests/test_e2e_10_mef_eline.py ..........ss.....x.....x................  [ 23%] …
```

Handled ConnectError

---

CHANGELOG.rst
kytos.json
main.py

Closes #521 
See updated changelog file and/or add any other summarized helpful information for reviewers
Running Kytos/mef_eline with 2023.2.2 without this fix and a bunch of EVCs, during the startup will generate many event for the same interface (basically one event per EVC):
```
2024-10-05 08:07:22,029 - INFO [kytos.napps.kytos/mef_eline] [main.py:798:handle_interface_link_up] (thread_pool_app_301) Event handle_interface_link_up Interface('mia_s10-eth31', 31, Switch('00:00:00:00:00:00:00:10'))
2024-10-05 08:07:22,046 - INFO [kytos.napps.kytos/mef_eline] [main.py:798:handle_interface_link_up] (thread_pool_app_301) Event handle_interface_link_up Interface('mia_s10-eth31', 31, Switch('00:00:00:00:00:00:00:10'))
2024-10-05 08:07:22,060 - INFO [kytos.napps.kytos/mef_eline] …
```

hotfix 2023.2.3: optimized logging when handling interface link up

---

CHANGELOG.rst
ui/k-toolbar/main.kytos

Closes #525
Heads-up: this PR sits on top of PR #522
See updated changelog file.
After applying this fix along with https://github.com/kytos-ng/ui/pull/99 we have the following result:
N/A

backport/hotfix for issue #525 into 2023.2 -- fix premature submit when press Enter while choosing endpoints for EVC creation

---

CHANGELOG.rst
ui/k-toolbar/main.kytos

Closes #529 
Heads-up: this PR sits on top of #531 
See updated changelog file.
After applying this patch, we have the following view:
N/A

backport/hotfix for issue #529 into 2024.1 -- fixed default collapsed path constraint options on EVC creation

---

CHANGELOG.rst
kytos.json
ui/k-info-panel/list_connections.kytos
ui/k-info-panel/show_circuit.kytos

Closes #544 
Backported node_name fixes to `base/2023.2.4`. If the switch names are available, they will show instead of the dpids.
The mef_eline UI was tested and no errors occurred.

Backport node_name fixes to 2023.2.4

---

CHANGELOG.rst
scripts/db/2023.2.0/001_update_default_queue.py
scripts/db/2023.2.0/README.md

Closes #548. Redo of #557
Adds a simple migration script for changing the default queue_id from `None` to `-1`.
This appears to work, modifying everything with a queue_id of None to -1.

Adds migration script to update the default queue_id from `None` to `-1`

---

CHANGELOG.rst
kytos.json
ui/k-toolbar/main.kytos

Closes #541 
Backport to 2023.2.5.
Issue #541 was being caused because all data typed into the vlan sections of the mef_eline UI were being treated as JSON data and were being parsed as such, which would then throw an error. To fix this, a check was implemented to see if the data was indeed JSON and if it needed to be parsed.
Tested the UI, and an error was no longer displayed when typing a string into the vlan section.

Backport "Fixed issue with parsed data" to 2023.2.5

---

CHANGELOG.rst
ui/k-info-panel/show_circuit.kytos
ui/k-toolbar/main.kytos

Closes #541
Summary
Issue #541 was being caused because all data typed into the vlan sections of the mef_eline UI were being treated as JSON data and were being parsed as such, which would then throw an error. To fix this, a check was implemented to see if the data was indeed JSON and if it needed to be parsed.
Local Tests
Tested the UI, and an error was no longer displayed when typing a string into the vlan section.

Fixed issue with parsed data

---

ui/k-info-panel/show_circuit.kytos

Closes #541
The mef_eline infopanel had the same issue as the toolbar. Data that was not JSON was being parsed as JSON and this threw an error.
The mef_eline infopanel was used and no json parse errors ocurred.

Backport "Fixed bug with parsed data in show_circuits.kytos" to 2023.2.5

---

CHANGELOG.rst
kytos.json
ui/k-info-panel/show_circuit.kytos
ui/k-toolbar/main.kytos

Closes #541 
Summary
Backport to 2024.1.6.
Issue #541  was being caused because all data typed into the vlan sections of the mef_eline UI were being treated as JSON data and were being parsed as such, which would then throw an error. To fix this, a check was implemented to see if the data was indeed JSON and if it needed to be parsed.
Local Tests
Tested the UI, and an error was no longer displayed when typing a string into the vlan section.

Backport "Fixed issue with parsed data" to 2024.1.6

---

CHANGELOG.rst
kytos.json
main.py
models/path.py
openapi.yml
tests/unit/test_main.py

Closes #551 
Fixed backporting error for paths. `primary_path` S_VLAN was not being updated when passing to `current_path`.
Modified DB so:
- `"current_path": Path([])`
- `"failover_path": Path([])`
- `"primary_path": **previous current_path with modified s_vlans**`
- `"dynamic_backup_path": false`
N/A

Backport: rechoose S_VLAN from primary path.

---

CHANGELOG.rst
models/evc.py
tests/unit/models/test_evc_deploy.py
tests/unit/models/test_link_protection.py

Closes #514 
- Now using new `flow_manager` requests `flows_by_switch` to deploy paths in the method `_send_flow_mods`.
- Modified content for requests when deleting path. Now only 1 is sent for most cases.
Created/removed EVCs and looked at installed/deleted flows.
```
collected 271 items
tests/test_e2e_06_topology.py ....                                       [  8%] …
```

Using one request per path.

---

CHANGELOG.rst
exceptions.py
models/evc.py
tests/unit/models/test_evc_deploy.py
tests/unit/models/test_link_protection.py

Closes #572 
Closes #574 
- Tried out the same case reported on issue 572 no longer happens
- Transition cases locally explored:
1) Dynamic inter EVPL UNI down but going up with UNIs down -> OK
2) Dynamic inter EVPL UNI down but going up with UNIs up -> OK
3) Dynamic inter EVPL UNI down and up with UNIs up with existing path -> OK
4) Dynamic inter EVPL UNI down but going up with UNIs going up concurrently -> OK
5) Static inter EVPL UNI down but going up with UNIs down -> OK
6) Static inter EVPL UNI down but going up with UNIs up -> OK
7) Static inter EVPL UNI down and up with UNIs up with existing path -> OK
8) Static inter EVPL UNI down but going up with UNIs going up concurrently -> OK
9) Intra EVPL initially UP, all UNIs go down then go up -> OK
10) Intra …

fix: try to handle uni interface up as link up for inter-EVCs

---

CHANGELOG.rst
exceptions.py
kytos.json
models/evc.py

Backport of https://github.com/kytos-ng/mef_eline/pull/573
- Unit tests didn't get backported as usual to simplify
Run one of the cases mentioned in the linked PR but with kytosd on version `2023.2`
```
_   __      _
| | / /     | |
| |/ / _   _| |_ ___  ___          _ __   __ _
|    \| | | | __/ _ \/ __| ______ | '_ \ / _` |
| |\  \ |_| | || (_) \__ \|______|| | | | (_| |
\_| \_/\__, |\__\___/|___/        |_| |_|\__, |
__/ |                             __/ |
|___/                             |___/
Welcome to Kytos SDN Platform!
Kytos website.: https://kytos-ng.github.io/about/
Documentation.: https://github.com/kytos-ng/documentation/tree/master/tutorials/napps
OF Address....: tcp://0.0.0.0:6653
WEB UI........: http://0.0.0.0:8181/
Kytos Version.: 2023.2.0 …
```

[release 2023.2.7] backport: fix: try to handle uni interface up as link up for inter-EVCs

---

CHANGELOG.rst
exceptions.py
kytos.json
models/evc.py

Backport of https://github.com/kytos-ng/mef_eline/pull/573
- Unit tests didn't get backported as usual to simplify
Run one of the cases mentioned in the linked PR but with kytosd on version `2024.1`
```
_   __      _
| | / /     | |
| |/ / _   _| |_ ___  ___          _ __   __ _
|    \| | | | __/ _ \/ __| ______ | '_ \ / _` |
| |\  \ |_| | || (_) \__ \|______|| | | | (_| |
\_| \_/\__, |\__\___/|___/        |_| |_|\__, |
__/ |                             __/ |
|___/                             |___/
Welcome to Kytos SDN Platform!
Kytos website.: https://kytos-ng.github.io/about/
Documentation.: https://github.com/kytos-ng/documentation/tree/master/tutorials/napps
OF Address....: tcp://0.0.0.0:6653
WEB UI........: http://0.0.0.0:8181/
Kytos Version.: 2024.1.2 …
```

[release 2024.1.7] backport: fix: try to handle uni interface up as link up for inter-EVCs

---

main.py
models/evc.py
models/path.py
openapi.yml
tests/unit/models/test_evc_deploy.py
tests/unit/models/test_link_protection.py
tests/unit/test_main.py

Closes #543 
- API request `PATCH /api/kytos/mef_eline/v2/evc/{evc_id}/redeploy` now allows paramenter `?avoid_vlan=true`.
Redeployed EVCs with new feature
Additionally ran e2e test [PR](https://github.com/kytos-ng/kytos-end-to-end-tests/pull/338#pullrequestreview-2478370898):
```
collected 274 items
tests/test_e2e_06_topology.py ....                                       [  8%] …
```

Added support to avoid previous `current_path` tag for redeployment

---

CHANGELOG.rst
kytos.json
main.py
models/evc.py
models/path.py
openapi.yml
tests/unit/models/test_evc_deploy.py
tests/unit/models/test_link_protection.py
tests/unit/models/test_path.py

Closes #580 
- Added support for `try_avoid_same_s_vlan` as parameter variable for `PATCH` redeploy for EVCs.
- `remove_current_flows()` will not longer try to delete `failover_path` flows.
Updated unit tests but not added missing ones.
N/A

Backport: Added redeploy feature to avoid s_vlan

---

CHANGELOG.rst
kytos.json
main.py
models/path.py
openapi.yml

Closes #566
Ignoring `primary_path` `s_vlan` so it can be populated with `current_path` `s_vlan`
Same as in the backport for 2023.2
N/A

Updated to update `primary_path` `s_vlan`

---

CHANGELOG.rst
models/evc.py
tests/unit/models/test_evc_deploy.py

Closes #585 
`remove_current_flows` parameter `current_path` was still being used, so I brought it back.
Early return when the TAG type was invalid (e.g. `!= "vlan") would have left EVC with a `current_path`
Tested the scenarios and added a unit test
N/A

Fixed current_path not being deleted

---

CHANGELOG.rst
ui/k-info-panel/list_connections.kytos
ui/k-info-panel/show_circuit.kytos

Closes #593 
Interface is a reserved keyword, so it was replaced with k_interface.
After applying the changes I no longer got an error for utilizing a reserved keyword.

Made changes for vue3sfcloader compatibility k-info-panel

---

ui/k-toolbar/main.kytos

Closes #595 
Fix the form fields `min. flexible hits`  and `SPF max path` changing any value that is not a number to "" (empty).
UI test:
- click the mef-eline NApp
- try entering any non-numeric value in the fields: **SPF max path cost**  and  **Min. flexible hits**

Fix fields displaying NAN values

---

ui/k-info-panel/show_circuit.kytos

Closes #597
Fix the error about $payload not defined, removing the offending code (line 859)
It seems a debug code that was left in the script.
All other code modifications were trailing whitespace that was automatically removed.
Test the UI.
- select the mef-eline NApp
- open the List of EVC and select one EVC from the list.
- click Save EVC
The logging tab will pop up the updated messege.
No browser´s console error should be triggered.

UI - Fix $payload undefined code

---

main.py
models/evc.py
tests/unit/test_main.py

Closes #488.
Consistency check will not longer warn that a `failover_path` has not been found.
Added bool `warn_if_not_path` at method parameter to deploy `failover_path`.
Created an dynamic EVC with no possible `failover_path`
N/A

Added bool to log warnning for failover path

---

CHANGELOG.rst
ui/k-info-panel/show_circuit.kytos

Closes #605 
The port numbers were missing from the Circuit Details info panel.
The port numbers can be seen again:

Fixed missing port numbers

---

CHANGELOG.rst
models/evc.py
tests/unit/models/test_link_protection.py

Closes #607
Tried in this scenario:
Create an EVC where a UNI is an NNI not related to the path, e.g. uni_a=01:2, uni_z=02:01 where there is a link 01:2 - 04:2 and primary_path is through the link 01:3 - 02:3
In Mininet turn down the link 01:2 - 04:2
Manually delete current_path from the EVC
Turn up the link 01:2 - 04:2. Everything related to the EVC is up but it will not re-deploy from the link-up
Tried to replicate with previous scenario
```
plugins: timeout-2.2.0, rerunfailures-13.0, anyio-4.3.0
collected 277 items
tests/test_e2e_01_kytos_startup.py .. …
```

Redeploy static EVC when link_up

---

CHANGELOG.rst
kytos.json
models/evc.py
requirements/dev.in
tests/unit/models/test_evc_deploy.py
tests/unit/models/test_link_protection.py
tests/unit/test_main.py

Closes #610
Link up from UNI will deploy correctly an EVC when it does not have a path.
Updated unit tests
Same as backport for 2023.2
```
collected 297 items                                                                                                                                                                                              
tests/unit/models/test_evc_base.py .................................                                                          [ 11%]
tests/unit/models/test_evc_deploy.py ........................................................................................ [ 40%]
tests/unit/models/test_link_protection.py ..................                                                                  [ 46%]
tests/unit/models/test_path.py …
```

Backport: Redeploy static EVC when link_up 2024.1

---

CHANGELOG.rst
kytos.json
models/evc.py
tests/unit/models/test_link_protection.py

Closes #609 
- Link up from UNI will deploy correctly an EVC when it does not have a path.
Tried [this](https://github.com/kytos-ng/mef_eline/pull/608#pullrequestreview-2564458471) scenario
```
collected 290 items
tests/unit/test_controllers.py ........                                                                                   [  2%]
tests/unit/test_db_models.py .........................                                                                    [ 11%]
tests/unit/test_main.py .............................................................................                     [ 37%]
tests/unit/test_scheduler.py .........                                                                                    [ 41%]
tests/unit/test_utils.py ......... …
```

Backport: Redeploy static EVC when link_up 2023.2

---

CHANGELOG.rst
ui/k-info-panel/list_connections.kytos

Closes #594
Added column `Path Types` to `View Connections` component to indicate if the EVC has a `primary_path`,  `backup_path` and `dynamic_backup_path` with values `static_primary`,  `static_backup` and `dynamic_backup_path` respectively and in that order.
Tried the filter
Created EVCs
N/A

Added new column `Path Types` column to `View Connections`

---

CHANGELOG.rst
models/path.py
tests/unit/models/test_path.py

Closes #620 
Same as the one on #620, it no longer happens, no longer leaks if it a link can't allocate a vlan:
```
❯ http PATCH http://0.0.0.0:8181/api/kytos/mef_eline/v2/evc/fb5a0d362cf34b/redeploy
HTTP/1.1 409 Conflict
content-length: 50
content-type: application/json
date: Mon, 10 Feb 2025 18:01:03 GMT
server: uvicorn
{
"response": "Circuit fb5a0d362cf34b is disabled."
}
❯ http http://0.0.0.0:8181/api/kytos/topology/v3/interfaces/00:00:00:00:00:00:00:02:2/tag_ranges | jq
{
"00:00:00:00:00:00:00:02:2": {
"available_tags": {
"vlan": [
[
1,
3798
],
[
3800,
4095
]
]
},
"tag_ranges": {
"vlan": [
[
1,
4095
]
]
},
"special_tags": {
"vlan": [
"untagged",
"any"
]
},
"special_available_tags": {
"vlan": [
"untagged",
"any"
]
}
}
}
```
- Now increated tag_ranges again …

fix: fixed Path `choose_vlans` to be all or nothing, if a path link fails to allocate a vlan

---

CHANGELOG.rst
kytos.json
models/evc.py
models/path.py
tests/unit/models/test_evc_deploy.py
tests/unit/models/test_path.py

Closes #623 (for additional information check out this [comment](https://github.com/kytos-ng/mef_eline/issues/623#issuecomment-2653853732))
- See updated changelog file
- On issue #623 there's still a potential timeout DB operation issue, on this PR it'll only fix the request for now, and also backported #620. 
- I simulated a pathfinder request retry, and it retried as expected and deployed the EVC:
```
kytos $> 2025-02-12 14:52:59,866 - WARNING [kytos.core.retry] (AnyIO worker thread) Retry #1 for get_paths, args: (EVC(3a8d3c9b603649, epl),), kwargs: {}, seconds since start: 30.04    
2025-02-12 14:53:03,069 - INFO [uvicorn.access] (MainThread) 127.0.0.1:59302 - "POST /api/kytos/pathfinder/v3/ HTTP/1.1" 200
2025-02-12 14:53:03,086 - INFO [kytos.napps.kytos/flow_manager] (AnyIO worker …
```

release 2023.2.10: fixed request timeout that could indefinitely hang + backported vlan path choose vlan fix

---

CHANGELOG.rst
kytos.json
models/path.py
tests/unit/models/test_path.py

Backporting PR https://github.com/kytos-ng/mef_eline/pull/621 to 2024.1
- Created EVC, simulated the same case
- Also ran unit tests
```
=========================================================================== 299 passed, 635 warnings in 11.96s ===========================================================================
```
Same as related PR

release: 2024.1.11: Fixed Path `choose_vlans` to be all or nothing

---

CHANGELOG.rst
models/path.py
tests/unit/models/test_path.py

Closes #425
Now for a path to be valid, there should be present an interface in and out. This is done by checking interfaces in pairs and comparing the switches.
Created EVCs from the issue
N/A

Extending validation of paths

---

main.py
models/evc.py
tests/unit/models/test_link_protection.py

Closes #579 
Deleted `get_interface_from_switch()` because the interfaces are gotten from the UNIs now.
Check on kytos console for `are_unis_active()`
TBA

Getting interfaces from UNIs instead of switches

---

CHANGELOG.rst
kytos.json
main.py
tests/unit/test_main.py
utils.py

Adds fixes for handle link down to 2024.1. Depends on kytos-ng/flow_manager#217.
Played around with this today. Flows are installing correctly, and vlans are properly being allocated/deallocated.

Backport fixed `handle_link_down`

---

CHANGELOG.rst
README.rst
main.py
tests/unit/test_main.py
utils.py

Closes #517, #575
Replaces the procedure for handling of link down events to ensure that the old_path is torn down before fully committing changes to the database.
This still needs some tweaking, but the general shape of the solution is here. Will have to develop a test harness which can replicate the old issue reliably.
Here's the latest E2E test report:
```
kytos-1  | Starting enhanced syslogd: rsyslogd.
kytos-1  | /etc/openvswitch/conf.db does not exist ... (warning).
kytos-1  | Creating empty database /etc/openvswitch/conf.db.
kytos-1  | Starting ovsdb-server.
kytos-1  | rsyslogd: error during config processing: omfile: chown for file '/var/log/syslog' failed: Operation not permitted [v8.2302.0 try https://www.rsyslog.com/e/2207 ]
kytos-1  | Configuring Open vSwitch system IDs. …
```

Redid handling of link down to ensure tear down of old path

---

CHANGELOG.rst
main.py
models/evc.py
tests/unit/test_main.py
tests/unit/test_utils.py
utils.py

Closes #622
Confirmed that the listed issue is related to issue #623 by locking a second EVC with:
```
def test2(evc):
from threading import Thread
def locking(evc):
with evc.lock:
while True:
continue
thread = Thread(target=locking, args=(evc,))
thread.start()
```
Added checks for EVC before acquiring lock to reduce the possibility of this happening again.
Replicated the issue but the problem is handled in another issue.
```
python3 -m pytest tests/ --reruns 2 -r fEr
collected 278 items …
```

Checking on EVCs before acquiring lock

---

CHANGELOG.rst
kytos.json
main.py

Backport of #632
Replaces usage of `deploy_to_path` in `handle_need_redeploy` with `deploy`
Seems to run as expected in local testing.
Here are the relevant E2E test results:
```
=================================================================== test session starts ===================================================================
platform linux -- Python 3.11.11, pytest-8.3.4, pluggy-1.5.0
rootdir: /home/ktmi/Documents/kytos-project2024/kytos-end-to-end-tests
plugins: anyio-4.3.0
collected 42 items                                                                                                                                        
tests/test_e2e_10_mef_eline.py ..........ss.....x........................                                                                           [100%] …
```

Backport fix for `handle_need redeploy`

---

main.py

Fixes faulty need_redeploy behaviour, where deployment to dynamic path would be done rather than to primary/backup path.
Running this locally, the behavior now matches the expected.
Issue was identified in E2E tests. E2E test now passes:
```
=================================================================== test session starts ===================================================================
platform linux -- Python 3.11.11, pytest-8.3.4, pluggy-1.5.0
rootdir: /home/ktmi/Documents/kytos-project/kytos-end-to-end-tests
plugins: anyio-4.3.0
collected 46 items                                                                                                                                        
tests/test_e2e_10_mef_eline.py ..........ss.....x........................ …
```

Fix handle_evc_need_redeploy to use `deploy` instead of `deploy_to_path`

---

CHANGELOG.rst
kytos.json
main.py
models/evc.py
tests/unit/models/test_path.py
tests/unit/test_main.py
tests/unit/test_utils.py
utils.py

Closes #635 
Added EVC checkup before acquiring lock
Tried link flaps and e2e `test_025_uni_link_up_static_path()`
Run unit tests:
```
================================================ test session starts =================================================
platform linux -- Python 3.11.2, pytest-8.0.1, pluggy-1.5.0
cachedir: .tox/py311/.pytest_cache
rootdir: /home/aldo/Desktop/old/mef_eline
configfile: pytest.ini
plugins: asyncio-0.23.5, cov-4.1.0, anyio-4.3.0
asyncio: mode=Mode.AUTO
collected 314 items                                                                                                  
tests/unit/models/test_evc_base.py .................................                                           [ 10%]
tests/unit/models/test_evc_deploy.py …
```

Added EVC checkup before acquiring lock

---

CHANGELOG.rst
kytos.json
main.py
models/evc.py
tests/unit/test_main.py
tests/unit/test_utils.py
utils.py

Closes #636 
Added EVC checkup before acquiring lock
Tried link flaps and e2e `test_025_uni_link_up_static_path()`
Unit tests updated:
```
==================================================================================================================================================== test session starts ====================================================================================================================================================
platform linux -- Python 3.9.9, pytest-7.2.1, pluggy-1.5.0
cachedir: .tox/py39/.pytest_cache
rootdir: /home/aldo/Desktop/back/mef_eline, configfile: pytest.ini
plugins: anyio-3.6.2, cov-4.0.0, asyncio-0.20.3
asyncio: mode=auto
collected 302 items …
```

Backport Added EVC checkup before acquiring lock

---

CHANGELOG.rst
ui/k-info-panel/list_connections.kytos
ui/k-info-panel/show_circuit.kytos
ui/k-toolbar/main.kytos

Closes #630 
There was a method called `onblur_dpid` used for the autocomplete that was actually supposed to be a computed property. Because of this, the autocomplete did not function as it should.
The autocomplete worked after the changes.

Fixed Autocomplete

---

CHANGELOG.rst
controllers/__init__.py
kytos.json
requirements/dev.in

Closes https://github.com/kytos-ng/kytos/issues/538
- Index creation timeout didn't get adjusted since the default is plenty when its first created
Local tests were done with https://github.com/kytos-ng/kytos/pull/541
```
coverage: OK ✔ in 54.34 seconds
lint: recreate env because env type changed from {'name': 'coverage', 'type': 'VirtualEnvRunner'} to {'name': 'lint', 'type': 'VirtualEnvRunner'}
lint: remove tox env folder /tmp/mef_eline/.tox/py311
lint: install_deps> python -I -m pip install -r requirements/dev.in
lint: commands[0]> python3 setup.py lint
running lint
Yala is running. It may take several seconds...
INFO: Finished isort
INFO: Finished pycodestyle
INFO: Finished pylint
[isort] Skipped 4 files
:) No issues found.
No linter error found. …
```

release 2024.1.15: DB controller now retries for `ExecutionTimeout` and `ConnectionFailure` instead of just `AutoReconnect`

---

main.py
models/evc.py

Follow up to kytos-ng/kytos#548
Tweaked the format of logging tracebacks to no longer replace the newline character `\n` with `, `
Tracebacks are easier to read now.
Not really relevant to E2E

Tweak formatting of logging tracebacks

---

CHANGELOG.rst
db/models.py
main.py
models/evc.py
models/path.py
openapi.yml
tests/unit/models/test_evc_base.py
tests/unit/models/test_evc_deploy.py

Closes #643 
Improved LOG, now notifies that all obtained paths were invalid and suggests to increase `max_paths`
Added `max_paths` field to EVC document. It is also updatable.
Deployed EVC for `00:00:00:00:00:00:00:16:5` and `00:00:00:00:00:00:00:11:1` with `"max_paths": 10`
To be added, [issue](https://github.com/kytos-ng/kytos-end-to-end-tests/issues/347). [PR](https://github.com/kytos-ng/kytos-end-to-end-tests/pull/353#pullrequestreview-2737449227)

Added `max_paths` to EVC document

---

main.py
tests/unit/test_main.py

Closes #654 
Added an early return when FLOW_ERROR is caught.
- If EVC is not found
- If EVC is archived
- If EVC is not enabled
Manually trigger FLOW_ERROR
Added unit test
N/A

Added early return for flow_mod error

---

ui/k-toolbar/main.kytos

Closes #660 
Within the `k-toolbar`, `jQuery` was replaced with `Axios`.
There is one example for both sync and async `Axios` in the code.
No errors occured and I was able to perform http requests within the `mef-eline` `k-toolbar`.
The requests failed successfully.
The requests went through successfully.

K-Toolbar: Replaced jQuery with Axios for HTTP Requests

---

CHANGELOG.rst
kytos.json
models/evc.py
scripts/console/2025.1.1/001_redeploy_set_queue.py
scripts/console/2025.1.1/README.md
tests/unit/models/test_evc_deploy.py

Closes #671 
- Backport of https://github.com/kytos-ng/mef_eline/pull/673/files
- Local tests ran (and documented) on this issue https://github.com/kytos-ng/mef_eline/issues/671
- I also ran the console scripts with 50 EVCs, redeployed as expected, then no longer did anymore since the `set_queue` now is now placed before `output`:
```
...: 
...: print("Finished!")
Checking EVCs with action_type set_queue...
It WOULD redeploy 50 EVCs
Finished!
Checking EVCs with action_type set_queue...
It WILL redeploy 50 EVCs
INFO [kytos.napps.kytos/flow_manager] (AnyIO worker thread) Send FlowMod from request command: delete, force: True, dpids: ['00:00:00:00:00:00:00:01', '00:00:00
:00:00:00:00:03'], flows[0, 1]: [{'cookie': 12253324356661394500, 'cookie_mask': …
```

release 2025.1.1: `set_queue` action is now set before `output`

---

CHANGELOG.rst
kytos.json
ui/k-toolbar/main.kytos

Closes https://github.com/kytos-ng/ui/issues/230
- Backport of PR #683 
- It depends on https://github.com/kytos-ng/ui/pull/231
- I tested it with a 2025.1 env from scratch:
```
_   __      _
| | / /     | |
| |/ / _   _| |_ ___  ___          _ __   __ _
|    \| | | | __/ _ \/ __| ______ | '_ \ / _` |
| |\  \ |_| | || (_) \__ \|______|| | | | (_| |
\_| \_/\__, |\__\___/|___/        |_| |_|\__, |
__/ |                             __/ |
|___/                             |___/
Welcome to Kytos SDN Platform!
Kytos website.: https://kytos-ng.github.io/about/
Documentation.: https://github.com/kytos-ng/documentation/tree/master/tutorials/napps
OF Address....: tcp://0.0.0.0:6653
WEB UI........: http://0.0.0.0:8181/
Kytos Version.: 2025.1.0
```
- Before the PR:
- After …

release 2025.1.2: fix: UI: k-toolbar primary and secondary constraints are now collapsed by default again

---

CHANGELOG.rst
models/evc.py
scripts/db/2025.2.0/000_quinq_evcs.py
scripts/db/2025.2.0/README.md
tests/unit/models/test_evc_deploy.py

Closes #509
Closes #648
Closes #650
Closes #649
Provided script to redeploy affected EVCs.
Modified flows for 2 scenarios when creating EVCs
- Numeric VLAN and Untagged VLAN, current flows:
```
{"00:00:00:00:00:00:00:01": [
{"match": {"in_port": 1, "dl_vlan": 100},
"actions": [
{"action_type": "set_vlan", "vlan_id": 1},
{"action_type": "output", "port": 4}],
"table_group": "evpl",
"priority": 20000},
{"match": {"in_port": 4, "dl_vlan": 1},
"actions": [{"action_type": "set_vlan", "vlan_id": 100},
{"action_type": "output", "port": 1}],
"table_group": "evpl",
"priority": 20000}],
"00:00:00:00:00:00:00:03": [
{"match": {"in_port": 1, "dl_vlan": 0},
"actions": [{"action_type": "push_vlan", "tag_type": "c"},
{"action_type": "set_vlan", "vlan_id": 1},
{"action_type": "output", "port": 3}], …
```

Removed qinq for VLAN translation

---

CHANGELOG.rst
ui/k-toolbar/main.kytos

Closes #691 
Requires and depends on https://github.com/kytos-ng/telemetry_int/pull/163
Tested 3 cases in the UI:
- Inter EVC with proxy_port_enabled: false
- Inter EVC with proxy_port_enabled: true (but without proxy port configured), confirmed that it didn't enabled and logged the error including addting the expected status_reason metadata
- Inter EVC without proxy_port_enabled set
```
2025-08-08 16:34:01,546 - INFO [kytos.napps.kytos/telemetry_int] (MainThread) Handling mef_eline.deployed on EVC id: 0f5f78c3670a4c
2025-08-08 16:34:01,546 - ERROR [kytos.napps.kytos/telemetry_int] (MainThread) Failed when handling mef_eline.deployed: EVC 0f5f78c3670a4c with proxy_port_enabled must have both proxy ports set, pp_a: None, pp_z: None. Analyze the error and you'll …
```

feat: ui: implemented k-dropdown to cover INT proxy_port_enabled options

---

CHANGELOG.rst
main.py
models/evc.py
tests/unit/test_main.py
tests/unit/test_utils.py
utils.py

Closes #618
Removes the check_disabled_components check from the process of creating/updating EVCs. This check created inconsistent behaviour between intra and inter switch EVCs. Network state shouldn't dictate whether an EVC definition is valid, except to validate that the required components exist. We have other checks in place for if the network components are enabled to handle what check_disabled is trying to do.
Seems to work as expected. Intra switch EVCs on disabled interfaces are able to be created/updated without issue.
This is most of the E2E tests. I'm just waiting on the last few to finish. In terms of relevant tests, they are all passing.
```
kytos-1  | Starting enhanced syslogd: rsyslogd.
kytos-1  | /etc/openvswitch/conf.db does not exist ... (warning).
kytos-1  | Creating …
```

Remove check_disabled when creating and updating evcs

---

CHANGELOG.rst
README.rst
main.py
tests/unit/test_main.py

Closes #698
Listening to changes of interface statuses
Needs `topology` [PR](https://github.com/kytos-ng/topology/pull/286)
Disabled and enabled interfaces to see if intra and inter EVCs would be DOWN or not
E2E tests from this [PR](https://github.com/kytos-ng/kytos-end-to-end-tests/pull/392) are passing but I am going to run them all just in case.

Now listening to interface status events

---

CHANGELOG.rst
main.py
models/evc.py
models/path.py
tests/unit/models/test_evc_deploy.py
tests/unit/models/test_path.py
tests/unit/test_main.py

Closes #686
Makes it so that the `try_setup_failover` process of consistency check is distributed across multiple threads through the event bus. This should minimize the timespan this process will use to hold multiple evc locks, and prevent resource contention with the `link_down` handler.
Everything appears to be properly handled. Failover paths continue to be properly setup. Will need to do further testing with link flaps to fully validate.
Will need to run E2E tests on this.

Multithreaded Setup Failover

---

CHANGELOG.rst
kytos.json
main.py
models/evc.py
models/path.py
tests/unit/models/test_evc_deploy.py
tests/unit/models/test_path.py
tests/unit/test_main.py

Partially closes #686
Makes it so that the `try_setup_failover` process of consistency check is distributed across multiple threads through the event bus. This should minimize the timespan this process will use to hold multiple evc locks, and prevent resource contention with the `link_down` handler.
Everything appears to be properly handled. Failover paths continue to be properly setup. Will need to do further testing with link flaps to fully validate.
Will need to run E2E tests on this.

Multithreaded Setup Failover for 2025.1

---

CHANGELOG.rst
ui/k-info-panel/list_connections.kytos
ui/k-info-panel/show_circuit.kytos

Closes #699
Path tables from `Circuit Details` now have accordion tables. At first only shows the links for each path which are collapsible to show details of the clicked link.
Changed default matching for the table from `View Connections`:
- Every row will be displayed if it matches any of the filters if any filter is used.
- If any filter is checked, only the rows that match the checked filters will be displayed.
Each collapsible table (link details) needs a unique class name. I chose to use: `f"accordion-{path_type}-{interface_a}-{interface_b}-{s-vlan}"`. For example `"accordion-Current path-00:00:00:00:00:00:00:01:4-00:00:00:00:00:00:00:03:3-1"`
Created EVCs with primary paths.
N/A
https://github.com/user-attachments/assets/07aac52d-cb99-4837-aa04-181cc76a8cfc …

Added accordion tables to path tables
